"""Versioned, read-only runtime capabilities pinned to the certified pg_v2_baseline catalog.

v2_runtime_contract.json is generated by scripts/db/build_v2_runtime_contract.py from the frozen
structural manifest; it is code, never rewritten at runtime. No Alembic imports, stamp, DDL,
settings lookup or secondary datasource.
"""
import json
from pathlib import Path

from sqlalchemy import text

CONTRACT_PATH = Path(__file__).with_name('v2_runtime_contract.json')
CONTRACT_REVISION = 'pg_v2_baseline'


def load_contract():
    """Fail closed on a missing, malformed, foreign or incomplete contract."""
    from ..execution.schema import E10SchemaNotReady

    try:
        contract = json.loads(CONTRACT_PATH.read_text())
        complete = (contract['revision'] == CONTRACT_REVISION
                    and isinstance(contract['functions'], dict) and contract['functions']
                    and all(isinstance(contract[k], list) and contract[k]
                            for k in ('triggers', 'evaluation_constraints', 'calibration_indexes')))
    except (OSError, ValueError, KeyError, TypeError):
        complete = False
    if not complete:
        raise E10SchemaNotReady(['v2_contract_incomplete'])
    return contract


def require_v2_capabilities(connection):
    from ..execution.schema import E10SchemaNotReady

    contract = load_contract()
    by_name = lambda row: row['name']
    # pg_get_functiondef qualifies names relative to search_path. The certified
    # baseline owns public; reject a shadow schema instead of checking another DB.
    if connection.execute(text('SELECT current_schema()')).scalar_one() != 'public':
        raise E10SchemaNotReady(['v2_public_schema_required'])
    function_rows = connection.execute(text("""
        SELECT p.proname, md5(pg_get_functiondef(p.oid))
        FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
        WHERE n.nspname='public' AND (p.proname LIKE 'v2_%' OR p.proname LIKE 'e04_%')
    """)).all()
    functions = dict(function_rows)
    if len(function_rows) != len(contract['functions']) or functions != contract['functions']:
        raise E10SchemaNotReady(['v2_function_contract'])
    triggers = [dict(r) for r in connection.execute(text("""
        SELECT r.relname AS relation, t.tgname AS name,
               pg_get_triggerdef(t.oid) AS definition, t.tgenabled,
               t.tgdeferrable, t.tginitdeferred
        FROM pg_trigger t JOIN pg_class r ON r.oid=t.tgrelid
        JOIN pg_namespace n ON n.oid=r.relnamespace
        WHERE n.nspname='public' AND (t.tgname LIKE 'v2_%' OR t.tgname LIKE 'e04_%')
    """)).mappings()]
    if sorted(triggers, key=by_name) != sorted(contract['triggers'], key=by_name):
        raise E10SchemaNotReady(['v2_trigger_contract'])
    constraints = [dict(r) for r in connection.execute(text("""
        SELECT conname AS name, pg_get_constraintdef(oid) AS definition,
               condeferrable, condeferred, convalidated
        FROM pg_constraint WHERE conrelid='public.evaluations'::regclass ORDER BY conname
    """)).mappings()]
    # Compared name-sorted in Python: SQL ORDER BY follows the database collation.
    if sorted(constraints, key=by_name) != sorted(contract['evaluation_constraints'], key=by_name):
        raise E10SchemaNotReady(['v2_evaluation_contract'])
    indexes = [dict(r) for r in connection.execute(text("""
        SELECT c.relname AS name, pg_get_indexdef(i.indexrelid) AS definition,
               i.indisvalid, i.indisready, i.indisunique, i.indnullsnotdistinct
        FROM pg_index i JOIN pg_class c ON c.oid=i.indexrelid
        WHERE i.indrelid='public.evaluations'::regclass AND c.relname LIKE 'uq_e04_%'
        ORDER BY c.relname
    """)).mappings()]
    if sorted(indexes, key=by_name) != sorted(contract['calibration_indexes'], key=by_name):
        raise E10SchemaNotReady(['v2_calibration_uniqueness_contract'])
