model: yolo26n-seg.pt
data: smear_segmentation_project/configs/yolo_rbc_1024_v1.yaml
task: segment
imgsz: 1024
epochs: 100
patience: 20
optimizer: auto
pretrained: true
seed: 47
deterministic: true
device: mps
cache: false
save: true
plots: true
project: smear_segmentation_project/runs/yolo26_seg
name: yolo26n_rbc_1024_v1
exist_ok: false
batch: 8
amp: true
