-- DBV2.4 TRANSFER PLAN
-- GENERATED AND VALIDATED BY DBV2.3
-- DO NOT EXECUTE DURING DBV2.3

-- Requires explicit GATE DBV2.3 and DBV2.4 authorization before execution.
-- Source and destination are distinct clusters. PostgreSQL has no native cross-database SELECT.
-- DBV2.4 transport: export only the 16 authorized tables from one REPEATABLE READ READ ONLY
-- source snapshot; load identical values into session-local pg_temp staging via COPY FROM STDIN.
-- This is a reviewed SQL plan with a transport step, NOT an executable cross-database installer.
-- Never load password_hash values into evidence/logs. No credential literals occur in this file.
-- UUID columns are copied explicitly. None of these 16 tables has identity/generated columns.
-- No FK/trigger disabling. No legacy data or scientific metadata is transformed.
BEGIN;
-- Destination must be the attested persistent BD-v2; verify cluster/host/database before BEGIN.
-- The operator must populate the temporary tables at the transport boundary below before proceeding.
CREATE TEMP TABLE "dbv24_src_datasets" (LIKE public."datasets") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_dataset_versions" (LIKE public."dataset_versions") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_clinical_identities" (LIKE public."clinical_identities") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_dataset_source_records" (LIKE public."dataset_source_records") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_identity_evidence" (LIKE public."identity_evidence") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_dataset_version_sources" (LIKE public."dataset_version_sources") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_dataset_split_assignments" (LIKE public."dataset_split_assignments") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_dataset_split_statistics" (LIKE public."dataset_split_statistics") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_dataset_split_validation_checks" (LIKE public."dataset_split_validation_checks") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_dataset_splits" (LIKE public."dataset_splits") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_dataset_materializations" (LIKE public."dataset_materializations") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_dataset_materialization_activations" (LIKE public."dataset_materialization_activations") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_dataset_split_images" (LIKE public."dataset_split_images") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_roles" (LIKE public."roles") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_users" (LIKE public."users") ON COMMIT DROP;
CREATE TEMP TABLE "dbv24_src_user_roles" (LIKE public."user_roles") ON COMMIT DROP;

-- TRANSPORT BOUNDARY (DBV2.4 ONLY): populate all explicit columns with COPY FROM STDIN.
-- Source export SELECT statements are comments, to run only on the READ ONLY source:
-- SELECT "id", "name", "source", "version", "description", "total_images", "num_classes", "class_names", "class_distribution", "license", "url", "local_path", "checksum", "created_at", "metadata", "provider", "source_type", "source_reference", "source_version" FROM public."datasets";
-- SELECT "id", "name", "semantic_version", "status", "grouping_strategy", "grouping_field", "stratification_strategy", "split_algorithm", "split_algorithm_version", "random_seed", "target_train_ratio", "target_val_ratio", "target_test_ratio", "positive_class", "class_mapping", "source_record_count", "methodology_json", "created_at", "generated_at", "validated_at", "frozen_at", "archived_at" FROM public."dataset_versions";
-- SELECT "id", "dataset_id", "identity_type", "source_identifier", "status", "metadata", "created_at", "updated_at" FROM public."clinical_identities";
-- SELECT "id", "dataset_id", "clinical_identity_id", "source_record_key", "tfds_index", "source_filename", "class_index", "class_name", "original_label", "project_label", "relative_source_key", "source_file_sha256", "decoded_pixel_sha256", "image_width", "image_height", "file_size_bytes", "identity_status", "metadata", "created_at", "updated_at" FROM public."dataset_source_records";
-- SELECT "id", "source_record_id", "clinical_identity_id", "evidence_type", "evidence_level", "mapping_method", "evidence_reference", "official_source_reference", "evidence_json", "created_at" FROM public."identity_evidence";
-- SELECT "dataset_version_id", "dataset_id", "role", "created_at" FROM public."dataset_version_sources";
-- SELECT "id", "dataset_version_id", "source_record_id", "clinical_identity_id", "split_name", "class_index", "class_name", "metadata", "created_at" FROM public."dataset_split_assignments";
-- SELECT "id", "dataset_version_id", "scope", "metric_name", "numeric_value", "text_value", "details_json", "computed_at" FROM public."dataset_split_statistics";
-- SELECT "id", "dataset_version_id", "check_name", "status", "observed_value", "expected_value", "details_json", "blocking_for_validation", "blocking_for_freeze", "executed_at" FROM public."dataset_split_validation_checks";
-- SELECT "id", "dataset_id", "split_name", "num_samples", "class_distribution", "split_strategy", "random_seed", "created_at", "metadata" FROM public."dataset_splits";
-- SELECT "id", "dataset_version_id", "attempt_number", "status", "reconciliation_status", "relative_root", "record_count", "manifest_metadata", "started_at", "completed_at", "failure_reason", "metadata", "created_at" FROM public."dataset_materializations";
-- SELECT "id", "dataset_version_id", "materialization_id", "dataset_family", "activated_at", "deactivated_at", "metadata" FROM public."dataset_materialization_activations";
-- SELECT "image_id", "dataset_id", "dataset_name", "dataset_source", "dataset_dir", "split_name", "class_index", "class_name", "relative_path", "absolute_path", "filename", "original_tfds_label", "project_label", "label_mapping_version", "image_width", "image_height", "file_size_bytes", "checksum_sha256", "created_at", "updated_at", "metadata", "dataset_version_id", "dataset_materialization_id" FROM public."dataset_split_images";
-- SELECT "id", "name", "created_at" FROM public."roles";
-- SELECT "id", "username", "email", "password_hash", "status", "created_at", "updated_at", "last_login_at", "disabled_at" FROM public."users";
-- SELECT "user_id", "role_id", "created_at" FROM public."user_roles";

-- No application writers may connect while transferring. Lock all authorized destination tables.
LOCK TABLE public."dataset_versions", public."datasets", public."roles", public."users", public."clinical_identities", public."dataset_materializations", public."dataset_split_statistics", public."dataset_split_validation_checks", public."dataset_splits", public."dataset_version_sources", public."user_roles", public."dataset_materialization_activations", public."dataset_source_records", public."dataset_split_images", public."dataset_split_assignments", public."identity_evidence" IN ACCESS EXCLUSIVE MODE;
DO $preflight$ BEGIN
 IF EXISTS (SELECT 1 FROM public."datasets") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: datasets'; END IF;
 IF (SELECT count(*) FROM (SELECT "id", "name", "source", "version", "description", "total_images", "num_classes", "class_names", "class_distribution", "license", "url", "local_path", "checksum", "created_at", "metadata", "provider", "source_type", "source_reference", "source_version" FROM pg_temp."dbv24_src_datasets") q) <> 2 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: datasets'; END IF;
 IF EXISTS (SELECT 1 FROM public."dataset_versions") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: dataset_versions'; END IF;
 IF (SELECT count(*) FROM (SELECT "id", "name", "semantic_version", "status", "grouping_strategy", "grouping_field", "stratification_strategy", "split_algorithm", "split_algorithm_version", "random_seed", "target_train_ratio", "target_val_ratio", "target_test_ratio", "positive_class", "class_mapping", "source_record_count", "methodology_json", "created_at", "generated_at", "validated_at", "frozen_at", "archived_at" FROM pg_temp."dbv24_src_dataset_versions") q) <> 1 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: dataset_versions'; END IF;
 IF EXISTS (SELECT 1 FROM public."clinical_identities") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: clinical_identities'; END IF;
 IF (SELECT count(*) FROM (SELECT "id", "dataset_id", "identity_type", "source_identifier", "status", "metadata", "created_at", "updated_at" FROM pg_temp."dbv24_src_clinical_identities") q) <> 201 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: clinical_identities'; END IF;
 IF EXISTS (SELECT 1 FROM public."dataset_source_records") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: dataset_source_records'; END IF;
 IF (SELECT count(*) FROM (SELECT "id", "dataset_id", "clinical_identity_id", "source_record_key", "tfds_index", "source_filename", "class_index", "class_name", "original_label", "project_label", "relative_source_key", "source_file_sha256", "decoded_pixel_sha256", "image_width", "image_height", "file_size_bytes", "identity_status", "metadata", "created_at", "updated_at" FROM pg_temp."dbv24_src_dataset_source_records") q) <> 27558 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: dataset_source_records'; END IF;
 IF EXISTS (SELECT 1 FROM public."identity_evidence") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: identity_evidence'; END IF;
 IF (SELECT count(*) FROM (SELECT "id", "source_record_id", "clinical_identity_id", "evidence_type", "evidence_level", "mapping_method", "evidence_reference", "official_source_reference", "evidence_json", "created_at" FROM pg_temp."dbv24_src_identity_evidence") q) <> 27558 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: identity_evidence'; END IF;
 IF EXISTS (SELECT 1 FROM public."dataset_version_sources") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: dataset_version_sources'; END IF;
 IF (SELECT count(*) FROM (SELECT "dataset_version_id", "dataset_id", "role", "created_at" FROM pg_temp."dbv24_src_dataset_version_sources") q) <> 1 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: dataset_version_sources'; END IF;
 IF EXISTS (SELECT 1 FROM public."dataset_split_assignments") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: dataset_split_assignments'; END IF;
 IF (SELECT count(*) FROM (SELECT "id", "dataset_version_id", "source_record_id", "clinical_identity_id", "split_name", "class_index", "class_name", "metadata", "created_at" FROM pg_temp."dbv24_src_dataset_split_assignments") q) <> 27558 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: dataset_split_assignments'; END IF;
 IF EXISTS (SELECT 1 FROM public."dataset_split_statistics") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: dataset_split_statistics'; END IF;
 IF (SELECT count(*) FROM (SELECT "id", "dataset_version_id", "scope", "metric_name", "numeric_value", "text_value", "details_json", "computed_at" FROM pg_temp."dbv24_src_dataset_split_statistics") q) <> 1 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: dataset_split_statistics'; END IF;
 IF EXISTS (SELECT 1 FROM public."dataset_split_validation_checks") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: dataset_split_validation_checks'; END IF;
 IF (SELECT count(*) FROM (SELECT "id", "dataset_version_id", "check_name", "status", "observed_value", "expected_value", "details_json", "blocking_for_validation", "blocking_for_freeze", "executed_at" FROM pg_temp."dbv24_src_dataset_split_validation_checks") q) <> 12 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: dataset_split_validation_checks'; END IF;
 IF EXISTS (SELECT 1 FROM public."dataset_splits") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: dataset_splits'; END IF;
 IF (SELECT count(*) FROM (SELECT "id", "dataset_id", "split_name", "num_samples", "class_distribution", "split_strategy", "random_seed", "created_at", "metadata" FROM pg_temp."dbv24_src_dataset_splits") q) <> 0 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: dataset_splits'; END IF;
 IF EXISTS (SELECT 1 FROM public."dataset_materializations") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: dataset_materializations'; END IF;
 IF (SELECT count(*) FROM (SELECT "id", "dataset_version_id", "attempt_number", "status", "reconciliation_status", "relative_root", "record_count", "manifest_metadata", "started_at", "completed_at", "failure_reason", "metadata", "created_at" FROM pg_temp."dbv24_src_dataset_materializations") q) <> 1 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: dataset_materializations'; END IF;
 IF EXISTS (SELECT 1 FROM public."dataset_materialization_activations") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: dataset_materialization_activations'; END IF;
 IF (SELECT count(*) FROM (SELECT "id", "dataset_version_id", "materialization_id", "dataset_family", "activated_at", "deactivated_at", "metadata" FROM pg_temp."dbv24_src_dataset_materialization_activations") q) <> 0 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: dataset_materialization_activations'; END IF;
 IF EXISTS (SELECT 1 FROM public."dataset_split_images") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: dataset_split_images'; END IF;
 IF (SELECT count(*) FROM (SELECT "image_id", "dataset_id", "dataset_name", "dataset_source", "dataset_dir", "split_name", "class_index", "class_name", "relative_path", "absolute_path", "filename", "original_tfds_label", "project_label", "label_mapping_version", "image_width", "image_height", "file_size_bytes", "checksum_sha256", "created_at", "updated_at", "metadata", "dataset_version_id", "dataset_materialization_id" FROM pg_temp."dbv24_src_dataset_split_images") q) <> 55116 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: dataset_split_images'; END IF;
 IF EXISTS (SELECT 1 FROM public."roles") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: roles'; END IF;
 IF (SELECT count(*) FROM (SELECT "id", "name", "created_at" FROM pg_temp."dbv24_src_roles" WHERE id IN (SELECT role_id FROM pg_temp.dbv24_src_user_roles)) q) <> 1 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: roles'; END IF;
 IF EXISTS (SELECT 1 FROM public."users") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: users'; END IF;
 IF (SELECT count(*) FROM (SELECT "id", "username", "email", "password_hash", "status", "created_at", "updated_at", "last_login_at", "disabled_at" FROM pg_temp."dbv24_src_users") q) <> 1 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: users'; END IF;
 IF EXISTS (SELECT 1 FROM public."user_roles") THEN RAISE EXCEPTION 'DESTINATION_NOT_EMPTY: user_roles'; END IF;
 IF (SELECT count(*) FROM (SELECT "user_id", "role_id", "created_at" FROM pg_temp."dbv24_src_user_roles") q) <> 1 THEN RAISE EXCEPTION 'SOURCE_COUNT_CHANGED_OR_STAGING_MISSING: user_roles'; END IF;
 IF EXISTS (SELECT 1 FROM pg_temp.dbv24_src_dataset_versions WHERE status='FROZEN' AND frozen_at IS NULL) THEN RAISE EXCEPTION 'FROZEN_TIMESTAMP_CANNOT_BE_PRESERVED'; END IF;
END $preflight$;

-- dataset_versions: explicit columns; approved DBV2.1 temporary lifecycle handling
INSERT INTO public."dataset_versions" ("id", "name", "semantic_version", "status", "grouping_strategy", "grouping_field", "stratification_strategy", "split_algorithm", "split_algorithm_version", "random_seed", "target_train_ratio", "target_val_ratio", "target_test_ratio", "positive_class", "class_mapping", "source_record_count", "methodology_json", "created_at", "generated_at", "validated_at", "frozen_at", "archived_at")
SELECT "id", "name", "semantic_version", CASE WHEN status='FROZEN' THEN 'VALIDATED' ELSE status END, "grouping_strategy", "grouping_field", "stratification_strategy", "split_algorithm", "split_algorithm_version", "random_seed", "target_train_ratio", "target_val_ratio", "target_test_ratio", "positive_class", "class_mapping", "source_record_count", "methodology_json", "created_at", "generated_at", "validated_at", "frozen_at", "archived_at" FROM pg_temp.dbv24_src_dataset_versions;

-- datasets: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."datasets" ("id", "name", "source", "version", "description", "total_images", "num_classes", "class_names", "class_distribution", "license", "url", "local_path", "checksum", "created_at", "metadata", "provider", "source_type", "source_reference", "source_version")
SELECT "id", "name", "source", "version", "description", "total_images", "num_classes", "class_names", "class_distribution", "license", "url", "local_path", "checksum", "created_at", "metadata", "provider", "source_type", "source_reference", "source_version" FROM pg_temp."dbv24_src_datasets";

-- roles: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."roles" ("id", "name", "created_at")
SELECT "id", "name", "created_at" FROM pg_temp."dbv24_src_roles" WHERE id IN (SELECT role_id FROM pg_temp.dbv24_src_user_roles);

-- users: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."users" ("id", "username", "email", "password_hash", "status", "created_at", "updated_at", "last_login_at", "disabled_at")
SELECT "id", "username", "email", "password_hash", "status", "created_at", "updated_at", "last_login_at", "disabled_at" FROM pg_temp."dbv24_src_users";

-- clinical_identities: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."clinical_identities" ("id", "dataset_id", "identity_type", "source_identifier", "status", "metadata", "created_at", "updated_at")
SELECT "id", "dataset_id", "identity_type", "source_identifier", "status", "metadata", "created_at", "updated_at" FROM pg_temp."dbv24_src_clinical_identities";

-- dataset_materializations: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."dataset_materializations" ("id", "dataset_version_id", "attempt_number", "status", "reconciliation_status", "relative_root", "record_count", "manifest_metadata", "started_at", "completed_at", "failure_reason", "metadata", "created_at")
SELECT "id", "dataset_version_id", "attempt_number", "status", "reconciliation_status", "relative_root", "record_count", "manifest_metadata", "started_at", "completed_at", "failure_reason", "metadata", "created_at" FROM pg_temp."dbv24_src_dataset_materializations";

-- dataset_split_statistics: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."dataset_split_statistics" ("id", "dataset_version_id", "scope", "metric_name", "numeric_value", "text_value", "details_json", "computed_at")
SELECT "id", "dataset_version_id", "scope", "metric_name", "numeric_value", "text_value", "details_json", "computed_at" FROM pg_temp."dbv24_src_dataset_split_statistics";

-- dataset_split_validation_checks: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."dataset_split_validation_checks" ("id", "dataset_version_id", "check_name", "status", "observed_value", "expected_value", "details_json", "blocking_for_validation", "blocking_for_freeze", "executed_at")
SELECT "id", "dataset_version_id", "check_name", "status", "observed_value", "expected_value", "details_json", "blocking_for_validation", "blocking_for_freeze", "executed_at" FROM pg_temp."dbv24_src_dataset_split_validation_checks";

-- dataset_splits: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."dataset_splits" ("id", "dataset_id", "split_name", "num_samples", "class_distribution", "split_strategy", "random_seed", "created_at", "metadata")
SELECT "id", "dataset_id", "split_name", "num_samples", "class_distribution", "split_strategy", "random_seed", "created_at", "metadata" FROM pg_temp."dbv24_src_dataset_splits";

-- dataset_version_sources: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."dataset_version_sources" ("dataset_version_id", "dataset_id", "role", "created_at")
SELECT "dataset_version_id", "dataset_id", "role", "created_at" FROM pg_temp."dbv24_src_dataset_version_sources";

-- user_roles: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."user_roles" ("user_id", "role_id", "created_at")
SELECT "user_id", "role_id", "created_at" FROM pg_temp."dbv24_src_user_roles";

-- dataset_materialization_activations: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."dataset_materialization_activations" ("id", "dataset_version_id", "materialization_id", "dataset_family", "activated_at", "deactivated_at", "metadata")
SELECT "id", "dataset_version_id", "materialization_id", "dataset_family", "activated_at", "deactivated_at", "metadata" FROM pg_temp."dbv24_src_dataset_materialization_activations";

-- dataset_source_records: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."dataset_source_records" ("id", "dataset_id", "clinical_identity_id", "source_record_key", "tfds_index", "source_filename", "class_index", "class_name", "original_label", "project_label", "relative_source_key", "source_file_sha256", "decoded_pixel_sha256", "image_width", "image_height", "file_size_bytes", "identity_status", "metadata", "created_at", "updated_at")
SELECT "id", "dataset_id", "clinical_identity_id", "source_record_key", "tfds_index", "source_filename", "class_index", "class_name", "original_label", "project_label", "relative_source_key", "source_file_sha256", "decoded_pixel_sha256", "image_width", "image_height", "file_size_bytes", "identity_status", "metadata", "created_at", "updated_at" FROM pg_temp."dbv24_src_dataset_source_records";

-- dataset_split_images: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."dataset_split_images" ("image_id", "dataset_id", "dataset_name", "dataset_source", "dataset_dir", "split_name", "class_index", "class_name", "relative_path", "absolute_path", "filename", "original_tfds_label", "project_label", "label_mapping_version", "image_width", "image_height", "file_size_bytes", "checksum_sha256", "created_at", "updated_at", "metadata", "dataset_version_id", "dataset_materialization_id")
SELECT "image_id", "dataset_id", "dataset_name", "dataset_source", "dataset_dir", "split_name", "class_index", "class_name", "relative_path", "absolute_path", "filename", "original_tfds_label", "project_label", "label_mapping_version", "image_width", "image_height", "file_size_bytes", "checksum_sha256", "created_at", "updated_at", "metadata", "dataset_version_id", "dataset_materialization_id" FROM pg_temp."dbv24_src_dataset_split_images";

-- dataset_split_assignments: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."dataset_split_assignments" ("id", "dataset_version_id", "source_record_id", "clinical_identity_id", "split_name", "class_index", "class_name", "metadata", "created_at")
SELECT "id", "dataset_version_id", "source_record_id", "clinical_identity_id", "split_name", "class_index", "class_name", "metadata", "created_at" FROM pg_temp."dbv24_src_dataset_split_assignments";

-- identity_evidence: explicit columns; DIRECT_INSERT_SELECT_COMPATIBLE
INSERT INTO public."identity_evidence" ("id", "source_record_id", "clinical_identity_id", "evidence_type", "evidence_level", "mapping_method", "evidence_reference", "official_source_reference", "evidence_json", "created_at")
SELECT "id", "source_record_id", "clinical_identity_id", "evidence_type", "evidence_level", "mapping_method", "evidence_reference", "official_source_reference", "evidence_json", "created_at" FROM pg_temp."dbv24_src_identity_evidence";

-- Restore the ORIGINAL status before COMMIT; frozen_at is preserved (preflight forbids NULL).
UPDATE public.dataset_versions AS d SET status=s.status FROM pg_temp.dbv24_src_dataset_versions AS s WHERE d.id=s.id AND s.status='FROZEN' AND d.status='VALIDATED';
SET CONSTRAINTS ALL IMMEDIATE;

-- Bidirectional exact row equality, including IDs, paths, hashes, NULLs and timestamps.
-- Comparisons involving password_hash return no values; errors name only the table.
DO $verify$ BEGIN
 IF EXISTS ((SELECT "id", "name", "source", "version", "description", "total_images", "num_classes", "class_names", "class_distribution", "license", "url", "local_path", "checksum", "created_at", "metadata", "provider", "source_type", "source_reference", "source_version" FROM public."datasets") EXCEPT ALL (SELECT "id", "name", "source", "version", "description", "total_images", "num_classes", "class_names", "class_distribution", "license", "url", "local_path", "checksum", "created_at", "metadata", "provider", "source_type", "source_reference", "source_version" FROM pg_temp."dbv24_src_datasets")) OR EXISTS ((SELECT "id", "name", "source", "version", "description", "total_images", "num_classes", "class_names", "class_distribution", "license", "url", "local_path", "checksum", "created_at", "metadata", "provider", "source_type", "source_reference", "source_version" FROM pg_temp."dbv24_src_datasets") EXCEPT ALL (SELECT "id", "name", "source", "version", "description", "total_images", "num_classes", "class_names", "class_distribution", "license", "url", "local_path", "checksum", "created_at", "metadata", "provider", "source_type", "source_reference", "source_version" FROM public."datasets")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: datasets'; END IF;
 IF EXISTS ((SELECT "id", "name", "semantic_version", "status", "grouping_strategy", "grouping_field", "stratification_strategy", "split_algorithm", "split_algorithm_version", "random_seed", "target_train_ratio", "target_val_ratio", "target_test_ratio", "positive_class", "class_mapping", "source_record_count", "methodology_json", "created_at", "generated_at", "validated_at", "frozen_at", "archived_at" FROM public."dataset_versions") EXCEPT ALL (SELECT "id", "name", "semantic_version", "status", "grouping_strategy", "grouping_field", "stratification_strategy", "split_algorithm", "split_algorithm_version", "random_seed", "target_train_ratio", "target_val_ratio", "target_test_ratio", "positive_class", "class_mapping", "source_record_count", "methodology_json", "created_at", "generated_at", "validated_at", "frozen_at", "archived_at" FROM pg_temp."dbv24_src_dataset_versions")) OR EXISTS ((SELECT "id", "name", "semantic_version", "status", "grouping_strategy", "grouping_field", "stratification_strategy", "split_algorithm", "split_algorithm_version", "random_seed", "target_train_ratio", "target_val_ratio", "target_test_ratio", "positive_class", "class_mapping", "source_record_count", "methodology_json", "created_at", "generated_at", "validated_at", "frozen_at", "archived_at" FROM pg_temp."dbv24_src_dataset_versions") EXCEPT ALL (SELECT "id", "name", "semantic_version", "status", "grouping_strategy", "grouping_field", "stratification_strategy", "split_algorithm", "split_algorithm_version", "random_seed", "target_train_ratio", "target_val_ratio", "target_test_ratio", "positive_class", "class_mapping", "source_record_count", "methodology_json", "created_at", "generated_at", "validated_at", "frozen_at", "archived_at" FROM public."dataset_versions")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: dataset_versions'; END IF;
 IF EXISTS ((SELECT "id", "dataset_id", "identity_type", "source_identifier", "status", "metadata", "created_at", "updated_at" FROM public."clinical_identities") EXCEPT ALL (SELECT "id", "dataset_id", "identity_type", "source_identifier", "status", "metadata", "created_at", "updated_at" FROM pg_temp."dbv24_src_clinical_identities")) OR EXISTS ((SELECT "id", "dataset_id", "identity_type", "source_identifier", "status", "metadata", "created_at", "updated_at" FROM pg_temp."dbv24_src_clinical_identities") EXCEPT ALL (SELECT "id", "dataset_id", "identity_type", "source_identifier", "status", "metadata", "created_at", "updated_at" FROM public."clinical_identities")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: clinical_identities'; END IF;
 IF EXISTS ((SELECT "id", "dataset_id", "clinical_identity_id", "source_record_key", "tfds_index", "source_filename", "class_index", "class_name", "original_label", "project_label", "relative_source_key", "source_file_sha256", "decoded_pixel_sha256", "image_width", "image_height", "file_size_bytes", "identity_status", "metadata", "created_at", "updated_at" FROM public."dataset_source_records") EXCEPT ALL (SELECT "id", "dataset_id", "clinical_identity_id", "source_record_key", "tfds_index", "source_filename", "class_index", "class_name", "original_label", "project_label", "relative_source_key", "source_file_sha256", "decoded_pixel_sha256", "image_width", "image_height", "file_size_bytes", "identity_status", "metadata", "created_at", "updated_at" FROM pg_temp."dbv24_src_dataset_source_records")) OR EXISTS ((SELECT "id", "dataset_id", "clinical_identity_id", "source_record_key", "tfds_index", "source_filename", "class_index", "class_name", "original_label", "project_label", "relative_source_key", "source_file_sha256", "decoded_pixel_sha256", "image_width", "image_height", "file_size_bytes", "identity_status", "metadata", "created_at", "updated_at" FROM pg_temp."dbv24_src_dataset_source_records") EXCEPT ALL (SELECT "id", "dataset_id", "clinical_identity_id", "source_record_key", "tfds_index", "source_filename", "class_index", "class_name", "original_label", "project_label", "relative_source_key", "source_file_sha256", "decoded_pixel_sha256", "image_width", "image_height", "file_size_bytes", "identity_status", "metadata", "created_at", "updated_at" FROM public."dataset_source_records")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: dataset_source_records'; END IF;
 IF EXISTS ((SELECT "id", "source_record_id", "clinical_identity_id", "evidence_type", "evidence_level", "mapping_method", "evidence_reference", "official_source_reference", "evidence_json", "created_at" FROM public."identity_evidence") EXCEPT ALL (SELECT "id", "source_record_id", "clinical_identity_id", "evidence_type", "evidence_level", "mapping_method", "evidence_reference", "official_source_reference", "evidence_json", "created_at" FROM pg_temp."dbv24_src_identity_evidence")) OR EXISTS ((SELECT "id", "source_record_id", "clinical_identity_id", "evidence_type", "evidence_level", "mapping_method", "evidence_reference", "official_source_reference", "evidence_json", "created_at" FROM pg_temp."dbv24_src_identity_evidence") EXCEPT ALL (SELECT "id", "source_record_id", "clinical_identity_id", "evidence_type", "evidence_level", "mapping_method", "evidence_reference", "official_source_reference", "evidence_json", "created_at" FROM public."identity_evidence")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: identity_evidence'; END IF;
 IF EXISTS ((SELECT "dataset_version_id", "dataset_id", "role", "created_at" FROM public."dataset_version_sources") EXCEPT ALL (SELECT "dataset_version_id", "dataset_id", "role", "created_at" FROM pg_temp."dbv24_src_dataset_version_sources")) OR EXISTS ((SELECT "dataset_version_id", "dataset_id", "role", "created_at" FROM pg_temp."dbv24_src_dataset_version_sources") EXCEPT ALL (SELECT "dataset_version_id", "dataset_id", "role", "created_at" FROM public."dataset_version_sources")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: dataset_version_sources'; END IF;
 IF EXISTS ((SELECT "id", "dataset_version_id", "source_record_id", "clinical_identity_id", "split_name", "class_index", "class_name", "metadata", "created_at" FROM public."dataset_split_assignments") EXCEPT ALL (SELECT "id", "dataset_version_id", "source_record_id", "clinical_identity_id", "split_name", "class_index", "class_name", "metadata", "created_at" FROM pg_temp."dbv24_src_dataset_split_assignments")) OR EXISTS ((SELECT "id", "dataset_version_id", "source_record_id", "clinical_identity_id", "split_name", "class_index", "class_name", "metadata", "created_at" FROM pg_temp."dbv24_src_dataset_split_assignments") EXCEPT ALL (SELECT "id", "dataset_version_id", "source_record_id", "clinical_identity_id", "split_name", "class_index", "class_name", "metadata", "created_at" FROM public."dataset_split_assignments")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: dataset_split_assignments'; END IF;
 IF EXISTS ((SELECT "id", "dataset_version_id", "scope", "metric_name", "numeric_value", "text_value", "details_json", "computed_at" FROM public."dataset_split_statistics") EXCEPT ALL (SELECT "id", "dataset_version_id", "scope", "metric_name", "numeric_value", "text_value", "details_json", "computed_at" FROM pg_temp."dbv24_src_dataset_split_statistics")) OR EXISTS ((SELECT "id", "dataset_version_id", "scope", "metric_name", "numeric_value", "text_value", "details_json", "computed_at" FROM pg_temp."dbv24_src_dataset_split_statistics") EXCEPT ALL (SELECT "id", "dataset_version_id", "scope", "metric_name", "numeric_value", "text_value", "details_json", "computed_at" FROM public."dataset_split_statistics")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: dataset_split_statistics'; END IF;
 IF EXISTS ((SELECT "id", "dataset_version_id", "check_name", "status", "observed_value", "expected_value", "details_json", "blocking_for_validation", "blocking_for_freeze", "executed_at" FROM public."dataset_split_validation_checks") EXCEPT ALL (SELECT "id", "dataset_version_id", "check_name", "status", "observed_value", "expected_value", "details_json", "blocking_for_validation", "blocking_for_freeze", "executed_at" FROM pg_temp."dbv24_src_dataset_split_validation_checks")) OR EXISTS ((SELECT "id", "dataset_version_id", "check_name", "status", "observed_value", "expected_value", "details_json", "blocking_for_validation", "blocking_for_freeze", "executed_at" FROM pg_temp."dbv24_src_dataset_split_validation_checks") EXCEPT ALL (SELECT "id", "dataset_version_id", "check_name", "status", "observed_value", "expected_value", "details_json", "blocking_for_validation", "blocking_for_freeze", "executed_at" FROM public."dataset_split_validation_checks")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: dataset_split_validation_checks'; END IF;
 IF EXISTS ((SELECT "id", "dataset_id", "split_name", "num_samples", "class_distribution", "split_strategy", "random_seed", "created_at", "metadata" FROM public."dataset_splits") EXCEPT ALL (SELECT "id", "dataset_id", "split_name", "num_samples", "class_distribution", "split_strategy", "random_seed", "created_at", "metadata" FROM pg_temp."dbv24_src_dataset_splits")) OR EXISTS ((SELECT "id", "dataset_id", "split_name", "num_samples", "class_distribution", "split_strategy", "random_seed", "created_at", "metadata" FROM pg_temp."dbv24_src_dataset_splits") EXCEPT ALL (SELECT "id", "dataset_id", "split_name", "num_samples", "class_distribution", "split_strategy", "random_seed", "created_at", "metadata" FROM public."dataset_splits")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: dataset_splits'; END IF;
 IF EXISTS ((SELECT "id", "dataset_version_id", "attempt_number", "status", "reconciliation_status", "relative_root", "record_count", "manifest_metadata", "started_at", "completed_at", "failure_reason", "metadata", "created_at" FROM public."dataset_materializations") EXCEPT ALL (SELECT "id", "dataset_version_id", "attempt_number", "status", "reconciliation_status", "relative_root", "record_count", "manifest_metadata", "started_at", "completed_at", "failure_reason", "metadata", "created_at" FROM pg_temp."dbv24_src_dataset_materializations")) OR EXISTS ((SELECT "id", "dataset_version_id", "attempt_number", "status", "reconciliation_status", "relative_root", "record_count", "manifest_metadata", "started_at", "completed_at", "failure_reason", "metadata", "created_at" FROM pg_temp."dbv24_src_dataset_materializations") EXCEPT ALL (SELECT "id", "dataset_version_id", "attempt_number", "status", "reconciliation_status", "relative_root", "record_count", "manifest_metadata", "started_at", "completed_at", "failure_reason", "metadata", "created_at" FROM public."dataset_materializations")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: dataset_materializations'; END IF;
 IF EXISTS ((SELECT "id", "dataset_version_id", "materialization_id", "dataset_family", "activated_at", "deactivated_at", "metadata" FROM public."dataset_materialization_activations") EXCEPT ALL (SELECT "id", "dataset_version_id", "materialization_id", "dataset_family", "activated_at", "deactivated_at", "metadata" FROM pg_temp."dbv24_src_dataset_materialization_activations")) OR EXISTS ((SELECT "id", "dataset_version_id", "materialization_id", "dataset_family", "activated_at", "deactivated_at", "metadata" FROM pg_temp."dbv24_src_dataset_materialization_activations") EXCEPT ALL (SELECT "id", "dataset_version_id", "materialization_id", "dataset_family", "activated_at", "deactivated_at", "metadata" FROM public."dataset_materialization_activations")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: dataset_materialization_activations'; END IF;
 IF EXISTS ((SELECT "image_id", "dataset_id", "dataset_name", "dataset_source", "dataset_dir", "split_name", "class_index", "class_name", "relative_path", "absolute_path", "filename", "original_tfds_label", "project_label", "label_mapping_version", "image_width", "image_height", "file_size_bytes", "checksum_sha256", "created_at", "updated_at", "metadata", "dataset_version_id", "dataset_materialization_id" FROM public."dataset_split_images") EXCEPT ALL (SELECT "image_id", "dataset_id", "dataset_name", "dataset_source", "dataset_dir", "split_name", "class_index", "class_name", "relative_path", "absolute_path", "filename", "original_tfds_label", "project_label", "label_mapping_version", "image_width", "image_height", "file_size_bytes", "checksum_sha256", "created_at", "updated_at", "metadata", "dataset_version_id", "dataset_materialization_id" FROM pg_temp."dbv24_src_dataset_split_images")) OR EXISTS ((SELECT "image_id", "dataset_id", "dataset_name", "dataset_source", "dataset_dir", "split_name", "class_index", "class_name", "relative_path", "absolute_path", "filename", "original_tfds_label", "project_label", "label_mapping_version", "image_width", "image_height", "file_size_bytes", "checksum_sha256", "created_at", "updated_at", "metadata", "dataset_version_id", "dataset_materialization_id" FROM pg_temp."dbv24_src_dataset_split_images") EXCEPT ALL (SELECT "image_id", "dataset_id", "dataset_name", "dataset_source", "dataset_dir", "split_name", "class_index", "class_name", "relative_path", "absolute_path", "filename", "original_tfds_label", "project_label", "label_mapping_version", "image_width", "image_height", "file_size_bytes", "checksum_sha256", "created_at", "updated_at", "metadata", "dataset_version_id", "dataset_materialization_id" FROM public."dataset_split_images")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: dataset_split_images'; END IF;
 IF EXISTS ((SELECT "id", "name", "created_at" FROM public."roles") EXCEPT ALL (SELECT "id", "name", "created_at" FROM pg_temp."dbv24_src_roles" WHERE id IN (SELECT role_id FROM pg_temp.dbv24_src_user_roles))) OR EXISTS ((SELECT "id", "name", "created_at" FROM pg_temp."dbv24_src_roles" WHERE id IN (SELECT role_id FROM pg_temp.dbv24_src_user_roles)) EXCEPT ALL (SELECT "id", "name", "created_at" FROM public."roles")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: roles'; END IF;
 IF EXISTS ((SELECT "id", "username", "email", "password_hash", "status", "created_at", "updated_at", "last_login_at", "disabled_at" FROM public."users") EXCEPT ALL (SELECT "id", "username", "email", "password_hash", "status", "created_at", "updated_at", "last_login_at", "disabled_at" FROM pg_temp."dbv24_src_users")) OR EXISTS ((SELECT "id", "username", "email", "password_hash", "status", "created_at", "updated_at", "last_login_at", "disabled_at" FROM pg_temp."dbv24_src_users") EXCEPT ALL (SELECT "id", "username", "email", "password_hash", "status", "created_at", "updated_at", "last_login_at", "disabled_at" FROM public."users")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: users'; END IF;
 IF EXISTS ((SELECT "user_id", "role_id", "created_at" FROM public."user_roles") EXCEPT ALL (SELECT "user_id", "role_id", "created_at" FROM pg_temp."dbv24_src_user_roles")) OR EXISTS ((SELECT "user_id", "role_id", "created_at" FROM pg_temp."dbv24_src_user_roles") EXCEPT ALL (SELECT "user_id", "role_id", "created_at" FROM public."user_roles")) THEN RAISE EXCEPTION 'ROW_PRESERVATION_MISMATCH: user_roles'; END IF;
 IF (SELECT count(*) FROM dataset_split_assignments WHERE dataset_version_id='d8c0cab5-09dd-597f-9de7-7ca01aee2ec2')<>27558 THEN RAISE EXCEPTION 'OFFICIAL_TOTAL_MISMATCH'; END IF;
 IF (SELECT count(DISTINCT clinical_identity_id) FROM dataset_split_assignments WHERE dataset_version_id='d8c0cab5-09dd-597f-9de7-7ca01aee2ec2')<>201 THEN RAISE EXCEPTION 'OFFICIAL_PATIENTS_MISMATCH'; END IF;
 IF (SELECT count(*) FROM dataset_split_assignments WHERE dataset_version_id='d8c0cab5-09dd-597f-9de7-7ca01aee2ec2' AND split_name='train')<>22180 THEN RAISE EXCEPTION 'OFFICIAL_SPLIT_MISMATCH: train'; END IF;
 IF (SELECT count(*) FROM dataset_split_assignments WHERE dataset_version_id='d8c0cab5-09dd-597f-9de7-7ca01aee2ec2' AND split_name='val')<>2693 THEN RAISE EXCEPTION 'OFFICIAL_SPLIT_MISMATCH: val'; END IF;
 IF (SELECT count(*) FROM dataset_split_assignments WHERE dataset_version_id='d8c0cab5-09dd-597f-9de7-7ca01aee2ec2' AND split_name='test')<>2685 THEN RAISE EXCEPTION 'OFFICIAL_SPLIT_MISMATCH: test'; END IF;
 IF (SELECT count(*) FROM dataset_split_images)<>55116 THEN RAISE EXCEPTION 'PHYSICAL_INVENTORY_MISMATCH'; END IF;
 IF (SELECT count(*) FROM (SELECT dataset_dir FROM dataset_split_images GROUP BY dataset_dir HAVING count(*)=27558) q)<>2 THEN RAISE EXCEPTION 'PHYSICAL_ROOTS_MISMATCH'; END IF;
END $verify$;
COMMIT;
-- All temporary staging disappears on COMMIT. Recompare persistent structural manifest.
-- No audit_events, experiments, runs, campaigns, artifacts, XAI, publications or E10 transfer.
