import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
const read=(path)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const layout=read('src/components/Layout.tsx');const app=read('src/App.tsx');const versions=read('src/pages/ModelVersions.tsx');const deployments=read('src/pages/Deployments.tsx');const api=read('src/services/api.ts');
test('renderiza un único menú padre Modelo IA y las vistas reales',()=>{assert.equal((layout.match(/<span>Modelo IA<\/span>/g)||[]).length,1);for(const label of ['Resumen','Entrenamientos','Evaluaciones','Modelos liberados','Despliegues','Trazabilidad','Explicabilidad','Predicciones','Dataset'])assert.match(layout,new RegExp(label));});
test('soporta expansión, persistencia, teclado y ARIA',()=>{for(const token of ['aria-expanded','aria-controls','ArrowRight','ArrowLeft','localStorage','aria-current'])assert.match(layout,new RegExp(token));});
test('mantiene todas las claves legacy',()=>{for(const key of ['dashboard','runs','clinical-evaluation','models','explainability','uploaded-predictions','dataset-browser','datasets','errors'])assert.match(app,new RegExp(`page === '${key}'`));});
test('registra las nuevas páginas sin opciones vacías',()=>{for(const key of ['model-versions','deployments','traceability'])assert.match(app,new RegExp(`page === '${key}'`));});
test('model versions incluye filtros, loading, vacío y error',()=>{for(const token of ['setLoading','setError','No hay model versions','setModel','setStatus','setLineage'])assert.match(versions,new RegExp(token));});
test('deployments usa endpoint real y no presenta acciones no autorizadas',()=>{assert.match(deployments,/getDeployments/);assert.doesNotMatch(deployments,/onClick|api\.(activate|deactivate|retire)/);});
test('las nuevas páginas no incluyen rutas físicas de modelos',()=>{for(const source of [versions,deployments]){assert.doesNotMatch(source,/best_model\.keras|checkpoint_path|model_path/);}});
test('API consume deployments activos mediante identidad gobernada',()=>{assert.match(api,/\/api\/deployments\/active/);assert.match(api,/\/api\/model-versions/);assert.doesNotMatch(versions,/checkpoint/);});
