import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
const read=(path)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const layout=read('src/components/Layout.tsx');const sidebar=read('src/components/navigation/AppSidebar.tsx');
const config=read('src/components/navigation/navigationConfig.ts');const icons=read('src/components/navigation/NavigationIcon.tsx');
const styles=read('src/styles.css');const app=read('src/App.tsx');const versions=read('src/pages/ModelVersions.tsx');const deployments=read('src/pages/Deployments.tsx');const api=read('src/services/api.ts');
test('renderiza Modelo IA con sus vistas existentes',()=>{assert.equal((config.match(/label: 'Modelo IA'/g)||[]).length,1);for(const label of ['Resumen','Ejecuciones','Evaluaciones','Comparación de modelos','Modelos liberados','Despliegues','Trazabilidad','Explicabilidad','Predicciones','Dataset','Datasets y modelos','Errores y logs'])assert.match(config,new RegExp(label));});
test('separa la operación en un único módulo Análisis de frotis',()=>{
  assert.equal((config.match(/label: 'Análisis de frotis'/g)||[]).length,1);
  assert.equal((config.match(/label: 'Cargar imágenes'/g)||[]).length,1);
  assert.equal((config.match(/routes\.smearUpload/g)||[]).length,1);
  assert.match(config,/pathPrefix: '\/frotis'/);
  assert.match(config,/pathPrefix: '\/modelo-ia'/);
  assert.ok(config.indexOf("label: 'Análisis de frotis'") < config.indexOf("label: 'Modelo IA'"));
});
test('soporta expansión, persistencia, teclado y ARIA',()=>{for(const token of ['aria-expanded','aria-controls','ArrowRight','ArrowLeft','localStorage','ml-dashboard.sidebar.collapsed'])assert.match(sidebar,new RegExp(token));});
test('usa configuración tipada, grupos e iconografía SVG única',()=>{for(const group of ['General','Experimentación','Gobernanza','Operación','Datos'])assert.match(config,new RegExp(group));assert.match(config,/NavigationIconName/);assert.match(icons,/<svg/);assert.doesNotMatch(config,/emoji/i);});
test('desktop expandido y contraído usan tokens sin márgenes rígidos',()=>{for(const token of ['--sidebar-expanded-width','--sidebar-collapsed-width','is-collapsed','grid-template-columns: auto'])assert.match(styles,new RegExp(token));});
test('mobile implementa drawer overlay, Escape, focus trap y retorno de foco',()=>{for(const token of ['mobileOpen','Escape','document.body.style.overflow','mobileTriggerRef.current?.focus','sidebar-overlay'])assert.match(sidebar+styles,new RegExp(token.replace('?','\\?')));assert.match(layout,/aria-label="Abrir navegación"/);});
test('tooltips funcionan por hover y focus en modo contraído',()=>{assert.match(sidebar,/data-tooltip/);assert.match(styles,/:hover::after/);assert.match(styles,/:focus-visible::after/);});
test('ruta activa usa prefijos con límite de segmento y expande su módulo',()=>{assert.match(config,/pathname\.startsWith\(`\$\{path\}\/`\)/);assert.match(sidebar,/activeModule/);assert.match(sidebar,/setOpenModules/);assert.match(sidebar,/NavLink/);assert.match(styles,/sidebar-link\.active/);});
test('datasource permanece fuera del menú y se conserva en enlaces',()=>{assert.match(layout,/Datasource activo/);assert.match(sidebar,/withAllowedQuery\(item\.path, \{ datasource \}\)/);assert.doesNotMatch(config,/datasource/i);});
test('registra las páginas existentes como rutas reales',()=>{for(const key of ['summary','runs','evaluations','comparison','explainability','predictions','dataset','datasetsModels','errorsLogs'])assert.match(app,new RegExp(`routes\\.${key}`));});
test('registra las rutas gobernadas de lista y detalle',()=>{for(const key of ['modelVersions','deployments','traceability','runDetail','modelVersionDetail','deploymentDetail'])assert.match(app,new RegExp(`routes\\.${key}`));});
test('model versions incluye filtros, loading, vacío y error',()=>{for(const token of ['setLoading','setError','No hay model versions','setModel','setStatus','setLineage'])assert.match(versions,new RegExp(token));});
test('deployments conecta smoke, activación confirmada y rollback inmutable',()=>{for(const token of ['getDeployments','smokeTestDeployment','activateDeployment','transitionDeployment','rollbackDeployment','confirmProduction'])assert.match(deployments,new RegExp(token));});
test('deployments muestra diagnóstico contextual y una sola expansión',()=>{for(const token of ['getDeploymentReadiness','Revisar despliegue','Cerrar revisión','expandedRowKey','renderExpandedRow','selectedDeploymentId','ActiveProductionModel','ProductionActivationModal'])assert.match(deployments,new RegExp(token));assert.doesNotMatch(deployments,/className="panel detail-panel"/);});
test('navegación no incluye rutas físicas o archivos internos',()=>{for(const source of [layout,sidebar,config,versions,deployments])assert.doesNotMatch(source,/best_model\.keras|checkpoint_path|model_path|\/Users\//);});
test('API consume modelos disponibles mediante identidad gobernada',()=>{assert.match(api,/\/api\/models\/available/);assert.match(api,/deployed_model_version_id/);assert.match(api,/\/api\/model-versions/);});
