"""E10.10 pure validation over evidence generated by the shared TRAIN path."""
from copy import deepcopy
from dataclasses import replace
from datetime import timedelta
from uuid import uuid4
import ast
from pathlib import Path

import pytest
from src.malaria_dl.campaigns.contracts import digest
from src.malaria_dl.execution.completion import (
    CompletionEvidence, TrainingCompletionValidator, TrainingCompletionContractV1,
    CompletionError, MissingTrainingEvaluation, MissingTerminalEvent, InvalidEventStream,
    TrainingResultsMismatch, ValidationPopulationMismatch, ThresholdMismatch,
    SelectedCheckpointMismatch, DatasetSnapshotMismatch, is_e10_governed, event_fingerprint)
from src.malaria_dl.execution.contracts import RunEventType as E
from src.malaria_dl.execution.train import train
from test_docker_train_integration import setup  # noqa: F401


@pytest.fixture(params=[False,True])
def scientific(setup,request):
    session,descriptor,trace,repo,reporter,emitter=setup
    session['configuration']['resolved']['execution']['calibrate_threshold']=request.param
    train(repo,session,descriptor,event_emitter=emitter)
    run={'id':session['run_id'],'run_type':'training','dataset_version_id':session['dataset']['dataset_version_id'],
         'parameters':{'training_results':{'schema_version':'training_results_v1','validation':reporter.events[-2].to_dict()['payload']}},
         'execution_parameters':{'model_configuration_e2':{'configuration':deepcopy(session['configuration']),'dataset':deepcopy(session['dataset'])}}}
    return CompletionEvidence(session,run,repo.records(session['run_id']),list(reporter.events),deepcopy(session['dataset']))


def validate(evidence,sealed=False):
    return TrainingCompletionValidator().validate(evidence,evidence.session['completion'],sealed=sealed)


def rehash(evidence):
    evidence.session['completion']['records_hash']=digest(evidence.records)
    evidence.events[-1]=replace(evidence.events[-1],payload={k:v for k,v in evidence.session['completion'].items() if k!='training_completion'})


def row(evidence,kind):
    return next(r['payload'] for r in evidence.records if r['kind']==kind)


def test_valid_contract_scientific_hashes_and_round_trip(scientific):
    value=validate(scientific)
    assert value.schema_version=='training_completion_v1'
    assert value.run_id==str(scientific.session['run_id'])
    assert value.evaluation_fingerprint==event_fingerprint(scientific.events[-2])
    assert value.training_results_hash==digest(scientific.run['parameters']['training_results'])
    assert value.records_hash==digest(scientific.records)
    assert not {'recall','f2','metrics','confusion_matrix','environment'} & value.to_dict().keys()
    assert TrainingCompletionContractV1.from_dict(value.to_dict())==value
    scientific.session['completion']['training_completion']=value.to_dict()
    assert validate(scientific,sealed=True)==value


def test_explicit_classification_and_no_legacy_obligations(scientific):
    assert is_e10_governed(scientific)
    legacy=replace(scientific,events=[])
    assert not is_e10_governed(legacy) and validate(legacy) is None
    scientific.session['completion']['training_completion']=validate(scientific).to_dict()
    assert is_e10_governed(legacy)
    with pytest.raises(InvalidEventStream):validate(legacy,sealed=True)


@pytest.mark.parametrize('case,error',[
    ('evaluation',MissingTrainingEvaluation),('terminal',MissingTerminalEvent),('failed',InvalidEventStream),
    ('gap',InvalidEventStream),('foreign_run',InvalidEventStream),('foreign_attempt',InvalidEventStream),
    ('double_eval',MissingTrainingEvaluation),('after_terminal',InvalidEventStream),
    ('parameters',TrainingResultsMismatch),('projection',TrainingResultsMismatch),('schema',TrainingResultsMismatch),
    ('population',ValidationPopulationMismatch),('dataset_id',DatasetSnapshotMismatch),('snapshot',DatasetSnapshotMismatch),
    ('checkpoint',SelectedCheckpointMismatch),('selected_samples',SelectedCheckpointMismatch),('hash',CompletionError),
    ('seal_missing',CompletionError),('seal_altered',CompletionError),('terminal_payload',CompletionError),
])
def test_missing_inconsistent_and_foreign_evidence_rejected(scientific,case,error):
    e=scientific;sealed=False
    if case=='evaluation':e.events[:]=[replace(x,sequence=i) for i,x in enumerate([x for x in e.events if x.event_type is not E.EVALUATION_COMPLETED],1)]
    if case=='terminal':e.events.pop()
    if case=='failed':e.events[-1]=replace(e.events[-1],event_type=E.TRAINING_FAILED)
    if case=='gap':e.events[0]=replace(e.events[0],sequence=999)
    if case=='foreign_run':e.events[0]=replace(e.events[0],run_id=uuid4())
    if case=='foreign_attempt':e.events[0]=replace(e.events[0],attempt_id=uuid4())
    if case=='double_eval':
        e.events.insert(-1,replace(e.events[-2],event_id=uuid4(),sequence=e.events[-1].sequence))
        e.events[-1]=replace(e.events[-1],sequence=e.events[-1].sequence+1)
    if case=='after_terminal':e.events.append(replace(e.events[0],event_id=uuid4(),sequence=len(e.events)+1))
    if case=='parameters':e.run['parameters']={}
    if case=='projection':e.run['parameters']['training_results']['validation']['metrics']['roc_auc']=.3
    if case=='schema':e.run['parameters']['training_results']['schema_version']='v2'
    if case=='population':
        for d in (e.session['dataset'],e.run['execution_parameters']['model_configuration_e2']['dataset'],e.campaign_dataset):d['counts']['val']+=1
    if case=='dataset_id':e.run['dataset_version_id']=str(uuid4())
    if case=='snapshot':e.session['dataset']['patient_assignment_fingerprint']='f'*64
    if case=='checkpoint':e.session['completion']['selection']['selected_epoch']=999;rehash(e)
    if case=='selected_samples':row(e,'calibration')['checkpoint_epoch']=999;rehash(e)
    if case=='hash':e.session['completion']['records_hash']='0'*64
    if case=='seal_missing':sealed=True
    if case=='seal_altered':
        value=validate(e).to_dict();value['training_results_hash']='0'*64
        e.session['completion']['training_completion']=value;sealed=True
    if case=='terminal_payload':e.events[-1]=replace(e.events[-1],payload={})
    with pytest.raises(error):validate(e,sealed)


def test_threshold_evidence_on_off(scientific):
    e=scientific
    if e.session['configuration']['resolved']['execution']['calibrate_threshold']:
        row(e,'calibration')['result']['threshold_used']=.123
        rehash(e)
    else:
        wire=e.events[-2].to_dict()['payload'];wire['threshold']['source']='validation_calibration'
        e.events[-2]=replace(e.events[-2],payload=wire)
        e.run['parameters']['training_results']['validation']=wire
    with pytest.raises(ThresholdMismatch):validate(e)


def test_samples_must_explain_actual_metrics(scientific):
    # Preserve an otherwise internally valid projection/event while changing the
    # selected model's durable scores; the scientific recomputation must reject it.
    for sample in row(scientific,'calibration')['samples']:sample['score']=.01
    rehash(scientific)
    with pytest.raises(TrainingResultsMismatch):validate(scientific)


def test_envelope_change_after_completion_detected_even_same_science(scientific):
    scientific.session['completion']['training_completion']=validate(scientific).to_dict()
    ev=scientific.events[-2]
    scientific.events[-2]=replace(ev,occurred_at=ev.occurred_at+timedelta(seconds=1))
    with pytest.raises(CompletionError):validate(scientific,sealed=True)


def test_completion_boundary_architecture():
    root=Path(__file__).resolve().parents[1]/'src/malaria_dl'
    tree=ast.parse((root/'execution/completion.py').read_text())
    for n in ast.walk(tree):
        if isinstance(n,ast.ImportFrom):assert not any(x in (n.module or '') for x in ('sqlalchemy','fastapi','local_execution','reporters','pathlib','persistence'))
        if isinstance(n,ast.Import):assert all(a.name not in ('os','pathlib','sqlite3','sqlalchemy') for a in n.names)
    for name in ('train.py','worker.py','emitter.py'):
        assert 'CompletionValidator' not in (root/'execution'/name).read_text()
