-- DBV2.2 + approved R1. Install exclusively via guarded Alembic v2.
CREATE TABLE public.artifacts (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid, artifact_type text NOT NULL, name text, path text NOT NULL, mime_type text, file_size_bytes bigint, checksum text, created_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb), artifact_uri text, artifact_status text DEFAULT CAST('available' AS text) NOT NULL, archived_at timestamp with time zone);

CREATE TABLE public.assessment_artifacts (attempt_id uuid NOT NULL, artifact_id uuid NOT NULL, sample_id uuid NOT NULL, role text NOT NULL, payload jsonb NOT NULL);

CREATE TABLE public.assessment_attempts (id uuid NOT NULL, identity_id uuid NOT NULL, owner uuid NOT NULL, host text NOT NULL, pid integer NOT NULL, ordinal integer NOT NULL, state text DEFAULT CAST('active' AS text) NOT NULL, artifact_root text NOT NULL, cause text, verification jsonb, started_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL, finished_at timestamp with time zone);

CREATE TABLE public.assessment_campaign_consumers (campaign_id uuid NOT NULL, member_id uuid NOT NULL, identity_id uuid NOT NULL);

CREATE TABLE public.assessment_final_locks (id uuid NOT NULL, identity_hash text NOT NULL, evidence jsonb NOT NULL, created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);

CREATE TABLE public.assessment_identities (id uuid NOT NULL, identity_hash text NOT NULL, training_run_id uuid NOT NULL, kind text NOT NULL, identity jsonb NOT NULL, canonical_identity text NOT NULL, structural_hash text GENERATED ALWAYS AS (assessment_structural_hash(identity)) STORED, created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);

CREATE TABLE public.assessment_results (attempt_id uuid NOT NULL, sample_id uuid NOT NULL, payload jsonb NOT NULL);

CREATE TABLE public.audit_events (id uuid NOT NULL, event_type text NOT NULL, action text NOT NULL, actor_user_id uuid, actor_username_snapshot text, resource_type text NOT NULL, resource_id text, request_method text NOT NULL, request_path text NOT NULL, correlation_id text NOT NULL, before_state jsonb, after_state jsonb, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, success boolean NOT NULL, error_code text, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.blood_samples (id uuid NOT NULL, case_id uuid NOT NULL, sample_code varchar(120) NOT NULL, specimen_type varchar(80) DEFAULT CAST('peripheral_blood' AS varchar) NOT NULL, collection_method varchar(120), anticoagulant varchar(120), collected_at timestamp with time zone, received_at timestamp with time zone, status varchar(20) DEFAULT CAST('registered' AS varchar) NOT NULL, notes text, metadata_json jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, created_by uuid NOT NULL, updated_by uuid, archived_at timestamp with time zone, archived_by uuid, source_system varchar(120), external_sample_id varchar(240), sample_identity_origin varchar(40) DEFAULT CAST('generated_by_capstone' AS varchar) NOT NULL, source_group_key varchar(240), ingestion_status varchar(20), expected_image_count integer);

CREATE TABLE public.campaign_attempts (id uuid NOT NULL, member_id uuid NOT NULL, ordinal integer NOT NULL, state text NOT NULL, training_run_id uuid, cause text, started_at timestamp with time zone DEFAULT now() NOT NULL, finished_at timestamp with time zone);

CREATE TABLE public.campaign_configurations (campaign_id uuid NOT NULL, configuration_hash text NOT NULL, configuration jsonb NOT NULL, canonical_configuration text NOT NULL, requests jsonb NOT NULL);

CREATE TABLE public.campaign_controlled_requests (id uuid NOT NULL, campaign_id uuid NOT NULL, member_id uuid NOT NULL, revision_id uuid NOT NULL, previous_attempt_id uuid NOT NULL, attempt_id uuid NOT NULL, run_id uuid NOT NULL, reason text NOT NULL, created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);

CREATE TABLE public.campaign_execution_events (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, campaign_id uuid NOT NULL, code text NOT NULL, created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);

CREATE TABLE public.campaign_members (id uuid NOT NULL, campaign_id uuid NOT NULL, configuration_hash text NOT NULL, seed integer NOT NULL, position integer NOT NULL, exclusion_reason text, state text DEFAULT CAST('pending' AS text) NOT NULL, accepted_attempt_id uuid);

CREATE TABLE public.campaign_technical_revisions (id uuid NOT NULL, campaign_id uuid NOT NULL, payload jsonb NOT NULL, canonical_payload text NOT NULL, payload_hash text NOT NULL, created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);

CREATE TABLE public.cell_classification_events (id uuid NOT NULL, classification_run_id uuid NOT NULL, cell_detection_id uuid, cell_prediction_id uuid, event_type varchar(120) NOT NULL, status varchar(40) NOT NULL, message_code varchar(80), message text, progress_current integer, progress_total integer, metadata_json jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.cell_classification_inputs (id uuid NOT NULL, classification_run_id uuid NOT NULL, detection_run_id uuid NOT NULL, cell_detection_id uuid NOT NULL, microscopy_image_id uuid NOT NULL, crop_id uuid, input_order integer NOT NULL, image_sequence_number integer NOT NULL, cell_index integer NOT NULL, cell_code varchar(40) NOT NULL, detector_key varchar(80) NOT NULL, detector_version varchar(40) NOT NULL, detector_algorithm_version varchar(80) NOT NULL, crop_sha256 char(64), crop_width_px integer, crop_height_px integer, detection_review_status_at_creation varchar(30), eligible boolean NOT NULL, exclusion_reason varchar(120), created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.cell_classification_reviews (id uuid NOT NULL, cell_prediction_id uuid NOT NULL, decision varchar(30) NOT NULL, reviewed_label varchar(20), comment text, actor_user_id uuid NOT NULL, created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);

CREATE TABLE public.cell_classification_runs (id uuid NOT NULL, analysis_run_id uuid NOT NULL, detection_run_id uuid NOT NULL, classification_run_code varchar(20) NOT NULL, production_model_id uuid NOT NULL, stage2_publication_id uuid NOT NULL, model_registry_id uuid NOT NULL, model_name varchar(160) NOT NULL, model_version varchar(120), model_snapshot jsonb NOT NULL, input_manifest_sha256 char(64) NOT NULL, status varchar(30) NOT NULL, input_count integer NOT NULL, eligible_count integer NOT NULL, excluded_count integer NOT NULL, processed_count integer DEFAULT 0 NOT NULL, parasitized_count integer DEFAULT 0 NOT NULL, uninfected_count integer DEFAULT 0 NOT NULL, near_threshold_count integer DEFAULT 0 NOT NULL, failed_count integer DEFAULT 0 NOT NULL, requested_by uuid NOT NULL, retry_of_run_id uuid, started_at timestamp with time zone, completed_at timestamp with time zone, failed_at timestamp with time zone, error_code varchar(80), error_message text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.cell_crops (id uuid NOT NULL, cell_detection_id uuid NOT NULL, relative_storage_key text NOT NULL, sha256 char(64) NOT NULL, file_size_bytes bigint NOT NULL, width_px integer NOT NULL, height_px integer NOT NULL, format varchar(20) NOT NULL, padding_px integer NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.cell_detection_events (id uuid NOT NULL, detection_run_id uuid NOT NULL, microscopy_image_id uuid, event_type varchar(100) NOT NULL, stage varchar(50) NOT NULL, status varchar(30) NOT NULL, message_code varchar(80), message text, progress_current integer, progress_total integer, metadata_json jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.cell_detection_runs (id uuid NOT NULL, analysis_run_id uuid NOT NULL, detection_run_code varchar(20) NOT NULL, detector_key varchar(80) NOT NULL, detector_version varchar(40) NOT NULL, algorithm_version varchar(80) NOT NULL, profile_snapshot jsonb NOT NULL, input_manifest_sha256 char(64) NOT NULL, status varchar(30) NOT NULL, image_count integer NOT NULL, processed_image_count integer DEFAULT 0 NOT NULL, component_count integer DEFAULT 0 NOT NULL, detection_count integer DEFAULT 0 NOT NULL, crop_count integer DEFAULT 0 NOT NULL, warning_count integer DEFAULT 0 NOT NULL, requested_by uuid NOT NULL, started_at timestamp with time zone, completed_at timestamp with time zone, failed_at timestamp with time zone, error_code varchar(80), error_message text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.cell_detections (id uuid NOT NULL, detection_run_id uuid NOT NULL, analysis_run_id uuid NOT NULL, connected_component_id uuid NOT NULL, analysis_run_image_id uuid NOT NULL, microscopy_image_id uuid NOT NULL, cell_index integer NOT NULL, cell_code varchar(40) NOT NULL, bbox_x integer NOT NULL, bbox_y integer NOT NULL, bbox_width integer NOT NULL, bbox_height integer NOT NULL, coordinate_space varchar(40) NOT NULL, detector_score double precision, automated_status varchar(30) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.cell_explanations (id uuid NOT NULL, cell_prediction_id uuid NOT NULL, method varchar(40) NOT NULL, method_version varchar(80) NOT NULL, status varchar(30) NOT NULL, last_conv_layer varchar(255), parameters_json jsonb NOT NULL, heatmap_storage_key text, heatmap_sha256 char(64), heatmap_file_size_bytes bigint, overlay_storage_key text, overlay_sha256 char(64), overlay_file_size_bytes bigint, width_px integer, height_px integer, started_at timestamp with time zone, completed_at timestamp with time zone, error_code varchar(80), error_message text, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.cell_predictions (id uuid NOT NULL, classification_run_id uuid NOT NULL, classification_input_id uuid NOT NULL, cell_detection_id uuid NOT NULL, crop_id uuid NOT NULL, prediction_status varchar(20) NOT NULL, raw_output jsonb NOT NULL, probability_parasitized double precision, probability_uninfected double precision, predicted_label varchar(20), predicted_class_index smallint, positive_label varchar(20) NOT NULL, positive_class_index smallint NOT NULL, threshold_used double precision NOT NULL, threshold_source varchar(120) NOT NULL, decision_margin double precision, near_threshold boolean DEFAULT FALSE NOT NULL, preprocessing_snapshot jsonb NOT NULL, inference_duration_ms double precision, error_code varchar(80), error_message text, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.clinical_identities (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, dataset_id uuid NOT NULL, identity_type text NOT NULL, source_identifier text NOT NULL, status text NOT NULL, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.dataset_materialization_activations (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, dataset_version_id uuid NOT NULL, materialization_id uuid NOT NULL, dataset_family text NOT NULL, activated_at timestamp with time zone DEFAULT now() NOT NULL, deactivated_at timestamp with time zone, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL);

CREATE TABLE public.dataset_materializations (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, dataset_version_id uuid NOT NULL, attempt_number integer NOT NULL, status text DEFAULT CAST('NOT_MATERIALIZED' AS text) NOT NULL, reconciliation_status text DEFAULT CAST('PENDING' AS text) NOT NULL, relative_root text NOT NULL, record_count bigint DEFAULT 0 NOT NULL, manifest_metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, started_at timestamp with time zone, completed_at timestamp with time zone, failure_reason text, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.dataset_source_records (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, dataset_id uuid NOT NULL, clinical_identity_id uuid, source_record_key text NOT NULL, tfds_index bigint, source_filename text, class_index integer NOT NULL, class_name text NOT NULL, original_label integer, project_label integer, relative_source_key text, source_file_sha256 text, decoded_pixel_sha256 text, image_width integer, image_height integer, file_size_bytes bigint, identity_status text NOT NULL, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.dataset_split_assignments (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, dataset_version_id uuid NOT NULL, source_record_id uuid NOT NULL, clinical_identity_id uuid NOT NULL, split_name text NOT NULL, class_index integer NOT NULL, class_name text NOT NULL, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.dataset_split_images (image_id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, dataset_id uuid, dataset_name text NOT NULL, dataset_source text NOT NULL, dataset_dir text NOT NULL, split_name text NOT NULL, class_index integer NOT NULL, class_name text NOT NULL, relative_path text NOT NULL, absolute_path text, filename text NOT NULL, original_tfds_label integer, project_label integer NOT NULL, label_mapping_version text NOT NULL, image_width integer, image_height integer, file_size_bytes bigint, checksum_sha256 text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, dataset_version_id uuid, dataset_materialization_id uuid);

CREATE TABLE public.dataset_split_statistics (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, dataset_version_id uuid NOT NULL, scope text NOT NULL, metric_name text NOT NULL, numeric_value numeric, text_value text, details_json jsonb, computed_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.dataset_split_validation_checks (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, dataset_version_id uuid NOT NULL, check_name text NOT NULL, status text NOT NULL, observed_value text, expected_value text, details_json jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, blocking_for_validation boolean DEFAULT FALSE NOT NULL, blocking_for_freeze boolean DEFAULT FALSE NOT NULL, executed_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.dataset_splits (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, dataset_id uuid, split_name text NOT NULL, num_samples integer, class_distribution jsonb DEFAULT CAST('{}' AS jsonb), split_strategy text, random_seed integer, created_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb));

CREATE TABLE public.dataset_version_sources (dataset_version_id uuid NOT NULL, dataset_id uuid NOT NULL, role text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.dataset_versions (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, name text NOT NULL, semantic_version text NOT NULL, status text DEFAULT CAST('DRAFT' AS text) NOT NULL, grouping_strategy text NOT NULL, grouping_field text NOT NULL, stratification_strategy text NOT NULL, split_algorithm text NOT NULL, split_algorithm_version text NOT NULL, random_seed integer NOT NULL, target_train_ratio numeric(8, 7) NOT NULL, target_val_ratio numeric(8, 7) NOT NULL, target_test_ratio numeric(8, 7) NOT NULL, positive_class text NOT NULL, class_mapping jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, source_record_count bigint DEFAULT 0 NOT NULL, methodology_json jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, generated_at timestamp with time zone, validated_at timestamp with time zone, frozen_at timestamp with time zone, archived_at timestamp with time zone);

CREATE TABLE public.datasets (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, name text NOT NULL, source text, version text, description text, total_images integer, num_classes integer, class_names text[], class_distribution jsonb DEFAULT CAST('{}' AS jsonb), license text, url text, local_path text, checksum text, created_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb), provider text, source_type text, source_reference text, source_version text);

CREATE TABLE public.deployed_model_versions (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, model_version_id uuid NOT NULL, checkpoint_artifact_id uuid NOT NULL, threshold_calibration_id uuid, deployment_name text NOT NULL, environment text NOT NULL, alias text NOT NULL, artifact_sha256 text NOT NULL, artifact_size_bytes bigint, threshold_value numeric NOT NULL, threshold_profile_snapshot jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, preprocessing_profile_snapshot jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, image_quality_policy_snapshot jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, label_mapping_snapshot jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, positive_label text DEFAULT CAST('parasitized' AS text) NOT NULL, score_name text DEFAULT CAST('probability_parasitized' AS text) NOT NULL, status text DEFAULT CAST('pending' AS text) NOT NULL, supersedes_deployment_id uuid, rollback_of_deployment_id uuid, deployed_at timestamp with time zone, retired_at timestamp with time zone, deployed_by text, retired_by text, deployment_reason text, retirement_reason text, created_at timestamp with time zone DEFAULT now() NOT NULL, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL);

CREATE TABLE public.environment_packages (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid, package_name text NOT NULL, package_version text, created_at timestamp with time zone DEFAULT now());

CREATE TABLE public.errors (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid, error_type text, error_message text, stack_trace text, script_name text, created_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb));

CREATE TABLE public.evaluation_ensemble_members (evaluation_id uuid NOT NULL, ordinal integer NOT NULL, model_version_id uuid NOT NULL, checkpoint_artifact_id uuid NOT NULL, weight numeric NOT NULL);

CREATE TABLE public.evaluations (id uuid DEFAULT gen_random_uuid(), run_id uuid NOT NULL, training_run_id uuid NOT NULL, model_version_id uuid, checkpoint_artifact_id uuid, dataset_version_id uuid NOT NULL, split text NOT NULL, evaluation_role text NOT NULL, purpose text NOT NULL, dataset_origin_id uuid, dataset_origin_role text, population_manifest_uri text, population_manifest_sha256 text, dataset_provenance_uri text, dataset_provenance_sha256 text, subject_kind text NOT NULL, protocol_version text NOT NULL, protocol_hash text NOT NULL, population_hash text NOT NULL, input_contract_hash text NOT NULL, comparison_contract_hash text NOT NULL, protocol_snapshot jsonb NOT NULL, source_kind text NOT NULL, source_record_key text NOT NULL, source_record_phase text NOT NULL, source_event_id uuid, event_kind text, event_phase text, event_key text, source_assessment_attempt_id uuid, threshold_used numeric NOT NULL, threshold_source text NOT NULL, calibration_id uuid, metric_definition text NOT NULL DEFAULT 'binary_nullable_v2', created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE public.execution_logs (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid, log_level text, message text, source text, created_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb));

CREATE TABLE public.experiment_execution_events (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, owner uuid NOT NULL, event text NOT NULL, payload jsonb NOT NULL, created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);

CREATE TABLE public.experiment_execution_gate (singleton boolean DEFAULT TRUE NOT NULL, owner uuid, db_pid integer, process_evidence jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, blocked_reason text, updated_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);

CREATE TABLE public.experimental_campaigns (id uuid NOT NULL, experiment_id uuid, name text NOT NULL, purpose text NOT NULL, state text DEFAULT CAST('draft' AS text) NOT NULL, dataset_version_id uuid NOT NULL, dataset_snapshot jsonb NOT NULL, dataset_evidence_id uuid NOT NULL, requested jsonb NOT NULL, protocol jsonb NOT NULL, environment jsonb NOT NULL, registry_snapshot jsonb, contract jsonb, canonical_contract text, contract_hash text, expected_count integer DEFAULT 0 NOT NULL, actor text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, frozen_at timestamp with time zone);

CREATE TABLE public.experiments (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, name text NOT NULL, description text, project_name text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb));

CREATE TABLE public.explainability_results (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid, prediction_id uuid, method text NOT NULL, image_path text, output_path text, true_label text, predicted_label text, score numeric, case_type text, last_conv_layer text, explanation_parameters jsonb DEFAULT CAST('{}' AS jsonb), success boolean DEFAULT TRUE, error_message text, created_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb));

CREATE TABLE public.identity_evidence (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, source_record_id uuid NOT NULL, clinical_identity_id uuid NOT NULL, evidence_type text NOT NULL, evidence_level text NOT NULL, mapping_method text NOT NULL, evidence_reference text, official_source_reference text, evidence_json jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.image_analysis_jobs (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, inference_run_id uuid NOT NULL, deployed_model_version_id uuid NOT NULL, model_version_id uuid NOT NULL, input_artifact_id uuid, source_image_id uuid, idempotency_key text, sample_id text, patient_id text, slide_id text, status text DEFAULT CAST('pending' AS text) NOT NULL, quality_status text DEFAULT CAST('not_assessed' AS text) NOT NULL, quality_metrics jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, threshold_used numeric, threshold_source text, summary jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, total_cells integer, positive_cells integer, started_at timestamp with time zone, completed_at timestamp with time zone, error_message text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL);

CREATE TABLE public.image_connected_components (id uuid NOT NULL, detection_run_id uuid NOT NULL, analysis_run_id uuid NOT NULL, analysis_run_image_id uuid NOT NULL, microscopy_image_id uuid NOT NULL, component_index integer NOT NULL, bbox_x integer NOT NULL, bbox_y integer NOT NULL, bbox_width integer NOT NULL, bbox_height integer NOT NULL, centroid_x double precision NOT NULL, centroid_y double precision NOT NULL, area_px integer NOT NULL, perimeter_px double precision, circularity double precision, solidity double precision, touches_border boolean NOT NULL, component_status varchar(30) NOT NULL, rejection_code varchar(80), metrics_json jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.image_ingestion_batches (id uuid NOT NULL, subject_id uuid NOT NULL, case_id uuid NOT NULL, sample_id uuid NOT NULL, slide_id uuid NOT NULL, acquisition_origin varchar(40) NOT NULL, source_system varchar(120), source_group_key varchar(240), expected_image_count integer, received_image_count integer DEFAULT 0 NOT NULL, status varchar(20) DEFAULT CAST('pending' AS varchar) NOT NULL, created_by uuid NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, completed_at timestamp with time zone, metadata_json jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL);

CREATE TABLE public.image_quality_assessments (id uuid NOT NULL, analysis_run_id uuid NOT NULL, analysis_run_image_id uuid NOT NULL, microscopy_image_id uuid NOT NULL, assessment_status varchar(20) NOT NULL, quality_verdict varchar(20) NOT NULL, integrity_verified boolean DEFAULT FALSE NOT NULL, checksum_verified boolean DEFAULT FALSE NOT NULL, decoded_successfully boolean DEFAULT FALSE NOT NULL, width_px integer NOT NULL, height_px integer NOT NULL, pixel_count bigint NOT NULL, channel_count integer, bit_depth integer, color_space varchar(80), analyzed_width_px integer NOT NULL, analyzed_height_px integer NOT NULL, analysis_scale double precision NOT NULL, brightness_mean double precision, brightness_p05 double precision, brightness_p50 double precision, brightness_p95 double precision, contrast_p95_p05 double precision, luminance_stddev double precision, entropy_bits double precision, laplacian_variance double precision, tenengrad_mean double precision, dark_pixel_ratio double precision, bright_pixel_ratio double precision, near_black_border_ratio double precision, usable_field_ratio double precision, warning_codes jsonb DEFAULT CAST('[]' AS jsonb) NOT NULL, failure_codes jsonb DEFAULT CAST('[]' AS jsonb) NOT NULL, metrics_json jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, started_at timestamp with time zone, completed_at timestamp with time zone, error_code varchar(80), error_message text, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.local_execution_jobs (id uuid NOT NULL, principal text NOT NULL, agent_id uuid NOT NULL, owner uuid NOT NULL, request_hash text NOT NULL, campaign_id uuid NOT NULL, run_id uuid, state text NOT NULL, session jsonb, heartbeat_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL, process jsonb, completion jsonb, exit_proof jsonb, result jsonb, created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);

CREATE TABLE public.microscopy_analysis_events (id uuid NOT NULL, analysis_run_id uuid NOT NULL, microscopy_image_id uuid, event_type varchar(80) NOT NULL, stage varchar(40) NOT NULL, status varchar(30) NOT NULL, message_code varchar(80), message text, progress_current integer, progress_total integer, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.microscopy_analysis_run_images (id uuid NOT NULL, analysis_run_id uuid NOT NULL, microscopy_image_id uuid NOT NULL, sequence_number integer NOT NULL, input_sha256 char(64) NOT NULL, input_file_size_bytes bigint NOT NULL, input_width_px integer NOT NULL, input_height_px integer NOT NULL, image_status_at_creation varchar(30) NOT NULL, quality_status varchar(20) DEFAULT CAST('pending' AS varchar) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.microscopy_analysis_runs (id uuid NOT NULL, ingestion_batch_id uuid NOT NULL, subject_id uuid NOT NULL, case_id uuid NOT NULL, sample_id uuid NOT NULL, slide_id uuid NOT NULL, run_code varchar(20) NOT NULL, run_status varchar(30) NOT NULL, active_stage varchar(30) NOT NULL, quality_gate_status varchar(20) NOT NULL, ready_for_analysis boolean DEFAULT FALSE NOT NULL, quality_profile_key varchar(80) NOT NULL, quality_profile_version varchar(40) NOT NULL, quality_algorithm_version varchar(40) NOT NULL, quality_profile_snapshot jsonb NOT NULL, input_manifest_sha256 char(64) NOT NULL, input_image_count integer NOT NULL, requested_by uuid NOT NULL, started_at timestamp with time zone, completed_at timestamp with time zone, failed_at timestamp with time zone, error_code varchar(80), error_message text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.microscopy_images (id uuid NOT NULL, slide_id uuid NOT NULL, image_code varchar(120) NOT NULL, storage_provider varchar(40) DEFAULT CAST('local' AS varchar) NOT NULL, storage_key text NOT NULL, original_filename text, mime_type varchar(120) NOT NULL, file_size_bytes bigint NOT NULL, sha256 char(64) NOT NULL, width_px integer NOT NULL, height_px integer NOT NULL, bit_depth integer, magnification numeric, objective_lens varchar(120), microscope_reference varchar(160), camera_reference varchar(160), captured_at timestamp with time zone, status varchar(20) DEFAULT CAST('registered' AS varchar) NOT NULL, metadata_json jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, created_by uuid NOT NULL, updated_by uuid, archived_at timestamp with time zone, archived_by uuid, acquisition_origin varchar(40) DEFAULT CAST('manual_upload' AS varchar) NOT NULL, source_system varchar(120), source_component_id varchar(240), source_image_name varchar(500), source_relative_path text, image_sequence_number integer, detected_format varchar(20), channel_count integer, color_space varchar(80), orientation varchar(80), ingestion_batch_id uuid);

CREATE TABLE public.model_versions (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, model_id uuid, version_name text, checkpoint_path text, final_model_path text, best_model_path text, training_run_id uuid, created_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb), model_name text, version_number integer, checkpoint_artifact_id uuid, artifact_uri text, artifact_sha256 text, artifact_size_bytes bigint, artifact_hash_reuse_justification text, framework text, framework_version text, preprocessing_profile_snapshot jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, class_mapping jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, input_signature jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, output_signature jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, status text DEFAULT CAST('discovered' AS text) NOT NULL, lineage_status text DEFAULT CAST('unresolved' AS text) NOT NULL, validated_at timestamp with time zone, approved_at timestamp with time zone, retired_at timestamp with time zone);

CREATE TABLE public.models (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, name text NOT NULL, model_type text NOT NULL, framework text, architecture text, description text, input_shape text, output_shape text, num_parameters bigint, pretrained boolean DEFAULT FALSE, pretrained_source text, created_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb));

CREATE TABLE public.predictions (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid, dataset_id uuid, image_id text, image_path text, true_label text, predicted_label text, score numeric, score_positive_label numeric, threshold numeric, is_correct boolean, case_type text, created_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb), image_analysis_job_id uuid, model_version_id uuid, deployed_model_version_id uuid, inference_run_id uuid, classifier_model_version_id uuid, detector_model_version_id uuid, prediction_scope text DEFAULT CAST('legacy_image' AS text) NOT NULL, cell_index integer, source_image_id uuid, bbox_x numeric, bbox_y numeric, bbox_width numeric, bbox_height numeric, crop_artifact_id uuid, explanation_artifact_id uuid, probability_parasitized numeric, probability_uninfected numeric, threshold_used numeric, predicted_class smallint, confidence_level text, quality_status text, review_status text DEFAULT CAST('unreviewed' AS text) NOT NULL, reviewed_label text, reviewed_by text, reviewed_at timestamp with time zone, evaluation_id uuid, dataset_source_record_id uuid, true_class smallint);

CREATE TABLE public.quality_assessment_queue_items (id uuid NOT NULL, analysis_run_id uuid NOT NULL, priority smallint DEFAULT 50 NOT NULL, status varchar(20) DEFAULT CAST('queued' AS varchar) NOT NULL, requested_by uuid NOT NULL, requested_at timestamp with time zone DEFAULT now() NOT NULL, started_at timestamp with time zone, completed_at timestamp with time zone, failed_at timestamp with time zone, attempt_count integer DEFAULT 0 NOT NULL, last_error_code varchar(80), last_error_message text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.quality_gate_decisions (id uuid NOT NULL, analysis_run_id uuid NOT NULL, decision varchar(30) NOT NULL, comment text NOT NULL, actor_user_id uuid NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.research_subjects (id uuid NOT NULL, subject_code varchar(120) NOT NULL, study_reference varchar(200), age_group varchar(80), biological_sex varchar(80), metadata_json jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, status varchar(20) DEFAULT CAST('active' AS varchar) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, created_by uuid, updated_by uuid, archived_at timestamp with time zone, archived_by uuid, source_system varchar(120), external_patient_id varchar(240));

CREATE TABLE public.roles (id uuid NOT NULL, name text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.run_checkpoint_policy (run_checkpoint_policy_id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid NOT NULL, model_name text, checkpoint_policy text NOT NULL, checkpoint_policy_config jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, selected_epoch integer, policy_satisfied boolean, selected_metric text, selected_metric_value numeric, min_recall_required numeric, val_recall_parasitized_selected numeric, val_f2_parasitized_selected numeric, val_specificity_selected numeric, val_auc_selected numeric, val_pr_auc_selected numeric, val_balanced_accuracy_selected numeric, prediction_collapse_detected boolean, all_epochs_collapsed boolean, checkpoint_warning text, checkpoint_path text, checkpoint_policy_summary_path text, model_metadata_path text, created_at timestamp with time zone DEFAULT now() NOT NULL, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, model_version_id uuid, checkpoint_artifact_id uuid);

CREATE TABLE public.run_clinical_metrics (run_clinical_metric_id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid NOT NULL, model_id uuid, model_name text, split_name text NOT NULL, threshold_used numeric, threshold_source text, accuracy numeric, precision_parasitized numeric, recall_parasitized numeric, sensitivity_parasitized numeric, specificity numeric, f1_parasitized numeric, f2_parasitized numeric, roc_auc_parasitized numeric, pr_auc_parasitized numeric, balanced_accuracy numeric, tn bigint NOT NULL, fp bigint NOT NULL, fn bigint NOT NULL, tp bigint NOT NULL, confusion_matrix jsonb DEFAULT CAST('[]' AS jsonb) NOT NULL, classification_report jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, prediction_distribution jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, prediction_collapse jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, label_mapping_version text DEFAULT CAST('clinical_v1_parasitized_positive' AS text) NOT NULL, raw_model_score_meaning text DEFAULT CAST('probability_parasitized' AS text) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, evaluation_id uuid NOT NULL, sample_count numeric GENERATED ALWAYS AS (CAST(tn AS numeric) + fp + fn + tp) STORED, auc_unavailability_reason text);

CREATE TABLE public.run_configurations (run_id uuid, architecture text NOT NULL, adapter_version text NOT NULL, optimizer text NOT NULL, learning_rate double precision NOT NULL, fine_tune_learning_rate double precision NOT NULL, batch_size integer NOT NULL, random_seed bigint NOT NULL, max_epochs integer NOT NULL, fine_tune_epochs integer NOT NULL, early_stopping boolean NOT NULL, early_stopping_patience integer NOT NULL, early_stopping_min_delta double precision NOT NULL, early_stopping_monitor text NOT NULL, early_stopping_mode text NOT NULL, restore_best_weights boolean NOT NULL, checkpoint_monitor text NOT NULL, checkpoint_mode text NOT NULL, dropout double precision NOT NULL, l2 double precision NOT NULL, input_height integer NOT NULL, input_width integer NOT NULL, input_channels integer NOT NULL, weights text NOT NULL, fine_tune_layers integer NOT NULL, normalization text NOT NULL, internal_preprocessing text, loss_function text NOT NULL, calibration_enabled boolean NOT NULL DEFAULT FALSE, default_threshold numeric NOT NULL DEFAULT 0.5, clinical_target_recall numeric NOT NULL, configuration_hash text NOT NULL, canonical_configuration text NOT NULL, optimizer_extensions jsonb NOT NULL DEFAULT '{}', extension_configuration jsonb NOT NULL DEFAULT '{}', provenance_snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE public.run_dataset_images (run_dataset_image_id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid NOT NULL, image_id uuid NOT NULL, split_name text NOT NULL, usage_context text NOT NULL, class_index integer NOT NULL, class_name text NOT NULL, relative_path text NOT NULL, filename text NOT NULL, batch_index integer, sample_index integer, used_for_training boolean DEFAULT FALSE NOT NULL, used_for_validation boolean DEFAULT FALSE NOT NULL, used_for_test boolean DEFAULT FALSE NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL);

CREATE TABLE public.run_image_predictions (run_image_prediction_id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid NOT NULL, image_id uuid, split_name text, usage_context text, filename text, relative_path text, true_label integer, true_label_name text, predicted_label integer, predicted_label_name text, probability_parasitized numeric, probability_uninfected numeric, raw_model_score numeric, raw_model_score_meaning text DEFAULT CAST('probability_parasitized' AS text) NOT NULL, threshold_used numeric, threshold_source text, is_correct boolean, case_type text, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.run_io_records (run_io_id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid NOT NULL, script_name text NOT NULL, command text, input_parameters jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, output_results jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, output_artifacts jsonb DEFAULT CAST('[]' AS jsonb) NOT NULL, dataset_metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, label_mapping_version text DEFAULT CAST('clinical_v1_parasitized_positive' AS text) NOT NULL, raw_model_score_meaning text DEFAULT CAST('probability_parasitized' AS text), created_at timestamp with time zone DEFAULT now() NOT NULL, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, run_type text, model_name text, model_metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, clinical_metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, dataset_version_id uuid, dataset_materialization_id uuid);

CREATE TABLE public.run_lineage (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, parent_run_id uuid NOT NULL, child_run_id uuid NOT NULL, relationship_type text NOT NULL, checkpoint_path text, checkpoint_artifact_id uuid, model_version_id uuid, confidence text DEFAULT CAST('explicit' AS text) NOT NULL, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.run_metrics (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid, metric_name text NOT NULL, metric_value numeric, metric_unit text, split_name text, class_name text, step integer, epoch integer, created_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb));

CREATE TABLE public.run_model_deployments (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid NOT NULL, deployed_model_version_id uuid NOT NULL, model_version_id uuid NOT NULL, role text DEFAULT CAST('primary' AS text) NOT NULL, ordinal integer DEFAULT 0 NOT NULL, weight numeric, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.run_threshold_calibration (run_threshold_calibration_id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid NOT NULL, model_name text, threshold_policy text DEFAULT CAST('target_recall' AS text) NOT NULL, threshold_source text DEFAULT CAST('validation_calibration' AS text) NOT NULL, threshold_selected numeric NOT NULL, default_threshold numeric DEFAULT 0.5 NOT NULL, target_recall numeric NOT NULL, target_recall_satisfied boolean, min_specificity numeric, validation_recall_at_threshold numeric, validation_specificity_at_threshold numeric, validation_precision_at_threshold numeric, validation_f1_at_threshold numeric, validation_f2_at_threshold numeric, validation_balanced_accuracy_at_threshold numeric, validation_pr_auc numeric, validation_roc_auc numeric, default_threshold_metrics jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, selected_threshold_metrics jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, candidate_count integer, threshold_warning text, calibration_split text DEFAULT CAST('val' AS text) NOT NULL, threshold_calibration_path text, model_metadata_path text, created_at timestamp with time zone DEFAULT now() NOT NULL, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, model_version_id uuid, calibration_artifact_id uuid, score_name text DEFAULT CAST('probability_parasitized' AS text) NOT NULL, label_mapping_version text DEFAULT CAST('clinical_v1_parasitized_positive' AS text) NOT NULL, positive_label text DEFAULT CAST('parasitized' AS text) NOT NULL, calibration_status text DEFAULT CAST('recorded' AS text) NOT NULL, default_evaluation_id uuid NOT NULL, selected_evaluation_id uuid NOT NULL);

CREATE TABLE public.runs (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, experiment_id uuid, model_id uuid, dataset_id uuid, run_name text, run_type text NOT NULL, status text NOT NULL, command text, script_name text, started_at timestamp with time zone, finished_at timestamp with time zone, duration_seconds numeric, user_name text, host_name text, working_directory text, git_commit text, git_branch text, python_version text, tensorflow_version text, keras_version text, platform text, machine text, processor text, gpu_available boolean, gpu_devices jsonb DEFAULT CAST('[]' AS jsonb), random_seed integer, parameters jsonb DEFAULT CAST('{}' AS jsonb), notes text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb), execution_type text, execution_parameters jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, fine_tuning_start_epoch integer, total_epochs integer, completed_epochs integer DEFAULT 0 NOT NULL, max_epochs integer, stopped_epoch integer, best_epoch integer, checkpoint_monitor text, checkpoint_mode text, best_validation_value double precision, early_stopping_enabled boolean, early_stopping_patience integer, early_stopping_min_delta double precision, restore_best_weights boolean, backend_version text, pipeline_version text, configuration jsonb, error_message text, dataset_version_id uuid, release_status text, release_updated_at timestamp with time zone, release_changed_by text, release_reason text, campaign_id uuid, peak_cpu_memory_bytes bigint, peak_gpu_memory_bytes bigint);

CREATE TABLE public.scientific_cases (id uuid NOT NULL, case_code varchar(120) NOT NULL, subject_id uuid, title varchar(240), description text, source_type varchar(30) NOT NULL, status varchar(20) DEFAULT CAST('draft' AS varchar) NOT NULL, priority varchar(10) DEFAULT CAST('normal' AS varchar) NOT NULL, metadata_json jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, created_by uuid NOT NULL, updated_by uuid, archived_at timestamp with time zone, archived_by uuid);

CREATE TABLE public.scientific_reviews (id uuid NOT NULL, entity_type varchar(40) NOT NULL, entity_id uuid NOT NULL, decision varchar(30) NOT NULL, comment text, actor_user_id uuid NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.scientific_validation_annotation_events (id uuid NOT NULL, annotation_id uuid NOT NULL, validation_session_id uuid, event_type varchar(20) NOT NULL, annotation_version integer NOT NULL, actor_user_id uuid NOT NULL, before_state jsonb, after_state jsonb NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.scientific_validation_annotations (id uuid NOT NULL, validation_session_id uuid, target_type varchar(20) NOT NULL, cell_detection_id uuid, analysis_run_id uuid, category varchar(120) NOT NULL, content text NOT NULL, version integer DEFAULT 1 NOT NULL, created_by uuid NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_by uuid NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, sample_id uuid);

CREATE TABLE public.scientific_validation_classification_runs (session_id uuid NOT NULL, classification_run_id uuid NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.scientific_validation_detection_runs (session_id uuid NOT NULL, detection_run_id uuid NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.scientific_validation_images (session_id uuid NOT NULL, microscopy_image_id uuid NOT NULL, image_sha256 char(64) NOT NULL, sequence_number integer NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.scientific_validation_sessions (id uuid NOT NULL, name varchar(200) NOT NULL, description text, datasource varchar(80) NOT NULL, protocol_key varchar(120) NOT NULL, protocol_version varchar(80) NOT NULL, matching_iou_threshold double precision NOT NULL, status varchar(30) DEFAULT CAST('draft' AS varchar) NOT NULL, initial_snapshot jsonb NOT NULL, snapshot_sha256 char(64) NOT NULL, created_by uuid NOT NULL, updated_by uuid NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, archived_at timestamp with time zone, archived_by uuid);

CREATE TABLE public.smear_analysis_summaries (id uuid NOT NULL, classification_run_id uuid NOT NULL, analysis_run_id uuid NOT NULL, detection_run_id uuid NOT NULL, outcome varchar(40) NOT NULL, eligible_cell_count integer NOT NULL, classified_cell_count integer NOT NULL, parasitized_candidate_count integer NOT NULL, uninfected_candidate_count integer NOT NULL, near_threshold_count integer NOT NULL, failed_prediction_count integer NOT NULL, parasitized_candidate_fraction double precision, maximum_probability_parasitized double precision, mean_probability_parasitized double precision, median_probability_parasitized double precision, per_image_summary jsonb NOT NULL, aggregation_policy_snapshot jsonb NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.smear_slides (id uuid NOT NULL, sample_id uuid NOT NULL, slide_code varchar(120) NOT NULL, smear_type varchar(20) NOT NULL, stain_type varchar(120), preparation_method varchar(160), prepared_at timestamp with time zone, status varchar(30) DEFAULT CAST('registered' AS varchar) NOT NULL, notes text, metadata_json jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, created_by uuid NOT NULL, updated_by uuid, archived_at timestamp with time zone, archived_by uuid);

CREATE TABLE public.stage2_model_publication_events (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, publication_id uuid NOT NULL, event_type text NOT NULL, actor text, event_at timestamp with time zone DEFAULT now() NOT NULL, model_version_id uuid NOT NULL, training_run_id uuid NOT NULL, evaluation_run_id uuid NOT NULL, datasource text NOT NULL, previous_status text, new_status text NOT NULL, reason text, correlation_id text, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL);

CREATE TABLE public.stage2_model_publications (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, datasource text NOT NULL, model_version_id uuid NOT NULL, training_run_id uuid NOT NULL, evaluation_run_id uuid NOT NULL, checkpoint_artifact_id uuid NOT NULL, scope text DEFAULT CAST('stage2' AS text) NOT NULL, status text DEFAULT CAST('active' AS text) NOT NULL, is_active boolean DEFAULT TRUE NOT NULL, published_at timestamp with time zone DEFAULT now() NOT NULL, published_by text, deactivated_at timestamp with time zone, deactivated_by text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, metadata jsonb DEFAULT CAST('{}' AS jsonb) NOT NULL);

CREATE TABLE public.synthetic_data_runs (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid, method text, num_images_generated integer, source_dataset_id uuid, output_path text, generation_parameters jsonb DEFAULT CAST('{}' AS jsonb), quality_checks jsonb DEFAULT CAST('{}' AS jsonb), created_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb));

CREATE TABLE public.train_execution_records (run_id uuid NOT NULL, kind text NOT NULL, phase text NOT NULL, record_key text NOT NULL, payload jsonb NOT NULL, created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL, event_id uuid, event_sequence numeric);

CREATE TABLE public.train_execution_revisions (attempt_id uuid NOT NULL, campaign_id uuid NOT NULL, revision_id uuid NOT NULL, created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);

CREATE TABLE public.train_execution_sessions (run_id uuid NOT NULL, attempt_id uuid, owner uuid NOT NULL, host text NOT NULL, parent_pid integer NOT NULL, child_pid integer, state text DEFAULT CAST('active' AS text) NOT NULL, configuration jsonb NOT NULL, dataset jsonb NOT NULL, environment jsonb NOT NULL, artifact_root text NOT NULL, cause text, started_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL, updated_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL, completion jsonb, verification jsonb);

CREATE TABLE public.training_history (id uuid DEFAULT pg_catalog.gen_random_uuid() NOT NULL, run_id uuid NOT NULL, epoch integer NOT NULL, loss numeric, accuracy numeric, precision_value numeric, recall_value numeric, auc numeric, val_loss numeric, val_accuracy numeric, val_precision numeric, val_recall numeric, val_auc numeric, learning_rate numeric, created_at timestamp with time zone DEFAULT now(), metadata jsonb DEFAULT CAST('{}' AS jsonb), phase text DEFAULT CAST('training' AS text) NOT NULL, train_loss numeric, train_accuracy numeric, train_specificity numeric, val_specificity numeric, train_f2 numeric, val_f2 numeric, train_balanced_accuracy numeric, val_balanced_accuracy numeric);

CREATE TABLE public.user_roles (user_id uuid NOT NULL, role_id uuid NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);

CREATE TABLE public.users (id uuid NOT NULL, username text NOT NULL, email text, password_hash text NOT NULL, status text DEFAULT CAST('active' AS text) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, last_login_at timestamp with time zone, disabled_at timestamp with time zone);

CREATE TABLE public.xai_artifacts (id uuid DEFAULT gen_random_uuid(), evidence_id uuid NOT NULL, artifact_id uuid, assessment_artifact_id uuid, role text NOT NULL, ordinal integer NOT NULL DEFAULT 0, storage_uri text NOT NULL, sha256 text NOT NULL, byte_size bigint NOT NULL, mime_type text NOT NULL, numeric_dtype text, tensor_shape integer[], axis_order text, coordinate_space text, availability text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE public.xai_evidence (id uuid DEFAULT gen_random_uuid(), ml_explanation_id uuid, cell_explanation_id uuid, assessment_attempt_id uuid, assessment_sample_id uuid, prediction_id uuid, cell_prediction_id uuid, evaluation_id uuid, dataset_source_record_id uuid, input_artifact_id uuid, microscopy_image_id uuid, run_id uuid, model_version_id uuid, checkpoint_artifact_id uuid NOT NULL, method_configuration_id uuid NOT NULL, target_layer text, prediction_score numeric, source_commit text NOT NULL, input_contract jsonb NOT NULL, input_contract_hash text NOT NULL, input_storage_uri text NOT NULL, input_sha256 text NOT NULL, checkpoint_sha256 text NOT NULL, target_class smallint NOT NULL, explained_output text NOT NULL, processing_stage text NOT NULL, seed bigint, background_manifest_uri text, background_manifest_sha256 text, environment_snapshot jsonb NOT NULL, generated_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE public.xai_interpretations (id uuid DEFAULT gen_random_uuid(), evidence_id uuid NOT NULL, author_user_id uuid NOT NULL, interpretation text NOT NULL, limitations text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), supersedes_id uuid);

CREATE TABLE public.xai_quantitative_evaluations (id uuid DEFAULT gen_random_uuid(), protocol_id uuid NOT NULL, metric_name text NOT NULL, membership_hash text NOT NULL, metric_value double precision, undefined_reason text, seed bigint, sample_count bigint NOT NULL, reference_annotation_id uuid, reference_annotation_version integer, reference_manifest_uri text, reference_manifest_sha256 text, details_uri text, details_sha256 text, evaluated_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE public.xai_specialist_reviews (id uuid DEFAULT gen_random_uuid(), interpretation_id uuid NOT NULL, reviewer_user_id uuid NOT NULL, decision text NOT NULL, rationale text NOT NULL, competence_snapshot jsonb NOT NULL, reviewed_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE public.xai_method_configurations (id uuid DEFAULT gen_random_uuid(), method text NOT NULL, implementation text NOT NULL, implementation_version text NOT NULL, parameters jsonb NOT NULL, canonical_configuration text NOT NULL, configuration_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE public.xai_region_attributions (xai_evidence_id uuid NOT NULL, region_type text NOT NULL, region_index integer NOT NULL, attribution_value double precision NOT NULL, rank integer, region_definition jsonb, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE public.xai_evaluation_protocols (id uuid DEFAULT gen_random_uuid(), metric_name text NOT NULL, metric_family text NOT NULL, protocol_name text NOT NULL, protocol_version text NOT NULL, parameters jsonb NOT NULL, normalization_strategy text NOT NULL, perturbation_strategy text, reference_definition jsonb, canonical_protocol text NOT NULL, protocol_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE public.xai_evaluation_members (evaluation_id uuid NOT NULL, xai_evidence_id uuid NOT NULL, member_role text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());

